### ISSUE TITLE
[avatar duotone appearance]: additional component appearance

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#1008]
After some research and discussion it was decided that tan additional appearance should be added to the avatar component.

The appearance is used in duotone.
Those are link to the design in Figma.

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19420%3A158935&t=aevYL5MkqeOU5zho-1

**Comment by yinonov** [comment]
this should not be worked on as it introduces changes in appearance model.
it should be blocked by a ticket that should be opened to apply changes to appearance model.
@AyalaBu please reflect those changes in Figma and open a ticket to apply those changes in dev.
see [VIV-844](https://jira.vonage.com/browse/VIV-844)

**Comment by rachelbt** [comment]
@AyalaBu 
https://vivid-wykt3m55gccg.deno.dev/components/avatar

**Comment by AyalaBu** [comment]
@rachelbt 
Looks great.
Does it mean that there will be no more outline avatar?

**Comment by rachelbt** [comment]
> @rachelbt Looks great. Does it mean that there will be no more outline avatar?

I'm leaving this to you to make the investigation :) 
I understood that it is not needed. but its not me to decide but the designers.

**Comment by rachelbt** [comment]
as was discusses - we are keeping the outline:
https://vonage.slack.com/archives/D03KLBB8K5Y/p1679211223715459
