### ISSUE TITLE
[duotone appearance]: color changes

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#1009]
After some research and discussion it was decided that the duotone appearance should be changed as described below:

Outline should change to 300 (Light theme)
Content should be changed to 600 (Light theme)

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=20330%3A124791&t=pc7HVw57404fU9aV-0

**Comment by yinonov** [comment]
Reflect in Figma please, alongside the appearance matrix

**Comment by rachelbt** [comment]
in the process of changing the dueatone color I'm trying to make some order in the appearance map-color-names.

- We are using same names for same purpose color - do we need it?
- We need an additional name for the scale - darker than soft + faint, lighter than primary (which is also intermediate).

Tried to sum it up in visual:

![image](https://user-images.githubusercontent.com/7512792/219946431-93859f19-36a4-4bf8-8dd9-89e694c922c7.png)

**Comment by rachelbt** [comment]
> We are using same names for same purpose color - do we need it? 
We need the duplication for different usages
> We need an additional name for the scale - darker than soft + faint, lighter than primary (which is also intermediate).
added only one additional name - pale
