### ISSUE TITLE
[dialog]: not supported in IOS 14

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#1011]
the <dialog> element is not supported in IOS 14.
there's a [polypill](https://github.com/GoogleChrome/dialog-polyfill).

Are we going to support IOS 14?

this was brought up by VBC after integrating vivid-3 dialog.

**Comment by olaf-k** [comment]
Apple doesn't support it, devices should migrate to iOS 15+.
![image](https://user-images.githubusercontent.com/1153034/217034287-e6ff8909-b756-4413-af4f-4c0be26facca.png)

**Comment by rachelbt** [comment]
> Apple doesn't support it, devices should migrate to iOS 15+. ![image](https://user-images.githubusercontent.com/1153034/217034287-e6ff8909-b756-4413-af4f-4c0be26facca.png)

I know it is not supported :) The question is if we are adding a polypill to backward capability...

**Comment by yinonov** [comment]
our official support matrix is 2 recent versions of major browsers. we should update our readme to state that.
