### ISSUE TITLE
CAPEX view

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#103]
- [ ] Only **merged PRs** should be included in CAPEX, not **merged issues**. 
- [ ] CAPEX should only include PRs with the status '**Done**'.
- [ ] '**Won't do**' and '**duplicate**' status should be ignored by CAPEX.
- [ ] Github Actions should assign closed PRs to the current sprint.
- [ ] Only closed and merged PRs should be added to the CAPEX board. PRs that are closed but not merged are not counted.
- [ ] PR merged with no _story point_ / _PREQ_ (product request) set, should create issue for that deficiency.
* _PREQs_ can be expressed by issues
* merged and closed PRs should be linked to PREQs issues in order to be included in CAPEX
  * problem is if there are multiple PRs linked to an issue, any of them closing will close the issue as well
  * we can instead, only mention PREQs issues from child issues as breaking PREQ to dedicated issues is obviously a right pattern

CAPEX view presented [here](https://github.com/orgs/Vonage/projects/3/views/18)

**Comment by rinaok** [comment]
- Github Actions should assign closed PRs to the current sprint.
- Only closed and merged PRs should be added to the CAPEX board. PRs that are closed but not merged are not counted.
- PRs without story points should fail.

**Comment by yinonov** [comment]
are epics needed in the process?
