### ISSUE TITLE
Sort out the design of data-grid's selection

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#1038]

**Comment by AyalaBu** [comment]
@YonatanKra 
This is the draft to data grid item:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=20733%3A128355&t=Re9mFSXt2ayDZoJm-1

Awaiting review

**Comment by YonatanKra** [comment]
Thanks.
I see every cell has 4 variations. What are they for?
Are they focus/selected/hover/etc. states?

**Comment by AyalaBu** [comment]
Yes
Every cell has 4 stats representations:

**Idle**: No background
**Hover**: Neutral 50
**Pressed**: Neutral 100
**Selected**: Neutral 200
