### ISSUE TITLE
[pagination]:creating component

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#1040]
The component of pagination is missing in Vivid 3

This is the design link in Figma:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=20641%3A128257&t=Wn1l803lLbYSh2A8-1

**Comment by AyalaBu** [comment]
@YonatanKra proposed creating a pagination component with dropdown such as in this example:
https://carbondesignsystem.com/components/pagination/usage

I had a conversation with the designers and all of them said that it is nice to have, but not must to have.
Therefore, in the meantime it was decided that shall a need arise a ticket with request will be opened.

Also,
This is the link to design draft:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=20763%3A154635&t=Wn1l803lLbYSh2A8-1

**Comment by rinaok** [comment]
https://jira.vonage.com/browse/VIV-964
