### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by Tamir198** [Vonage/vivid-3#1042]
### Description

Hey, when you click on "Vivid project components' view" link: 

![image](https://user-images.githubusercontent.com/34707669/221439271-1a61f640-2caf-4f93-9960-7b2432d07002.png)

This is what you see: 

![image](https://user-images.githubusercontent.com/34707669/221439313-0ae1dd93-d29a-4b48-bfc2-692cd7778d88.png)

### Component(s) impacted

not relevant

### Browser

Chrome

### Vivid Web Components version

not relevant

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

   not relevant

### CodeSandbox example

not relevant

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by olaf-k** [comment]
fixed, thanks!
