### ISSUE TITLE
select options view

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#1048]
currently the behaviour of the opened options are the same as in Fast but this is not like native select.
If we linit the select width the option-text is wrapped into lines and look bad:
![image](https://user-images.githubusercontent.com/7512792/222144969-993a0f15-b874-4512-83d8-2728bcc3cb96.png)

- We will change the option behaviur to match native - min-width: 100%, max-width: max-content.
- If the select is set to be smaller that the text inside - we will set ellipses.
-

**Comment by rachelbt** [comment]
The problem with min-width & width is when using a popup that is positioned absolute.
For better use in popup I added part to the popup wrapper and this way it will be easier to control it according to our needs.

**Comment by olaf-k** [comment]
> * We will change the option behaviur to match native - min-width: 100%, max-width: max-content.
> * If the select is set to be smaller that the text inside - we will set ellipses.

so, the select will resize based on the longest option as in native? and if the user forces it to be smaller, ellipses. am I getting this right?
