### ISSUE TITLE
[tooltip]: allow for custom text alignment

### ISSUE THREAD

**Issue by olaf-k** [Vonage/vivid-3#1050]
the `text` is currently left aligned by default, it should be easy to add an `align` (start/center/end) option.

**Comment by rachelbt** [comment]
basically text alignment is inherited in shadow dom. 
Because we do not have any text-align property on the tooltip, setting text-align: center  on its wrapper is good enough:
![image](https://user-images.githubusercontent.com/7512792/222416925-9ff525ed-cf34-4d35-a8e1-ec4de8cd8f1d.png)

**Comment by rinaok** [comment]
> basically text alignment is inherited in shadow dom. Because we do not have any text-align property on the tooltip, setting text-align: center on its wrapper is working: ![image](https://user-images.githubusercontent.com/7512792/222416925-9ff525ed-cf34-4d35-a8e1-ec4de8cd8f1d.png)

@rachelbt @olaf-k  Maybe we should just add an example like that to the docs?

**Comment by olaf-k** [comment]
> basically text alignment is inherited in shadow dom. Because we do not have any text-align property on the tooltip, setting text-align: center on its wrapper is working: 

I always forget that inheritable styles can traverse the SD. thanks Rach!
