### ISSUE TITLE
[Select with icon]:needs development

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#1068]
Select component does not support **_select + icon_** variant.
This variant is needed and was requested by the designers.

Link to Figma:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A80907&t=lZMEXSKWlxiQ3V0L-1

**Comment by rachelbt** [comment]
please varify:
https://vivid-4ns4frjgza60.deno.dev/components/select

**Comment by AyalaBu** [comment]
Looks great except of some padding issue.
Does it need a separate ticket?
