### ISSUE TITLE
[new icons]: need to be added to UI Kit

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#1078]
New icons were created for the Whiteboard and need to be added to our icons kit.
This is the link:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=959%3A14576&t=Mb30MFWq4g5BFj9y-1

![Image](https://user-images.githubusercontent.com/106529909/226310778-ab8de198-7e4b-417a-b3a5-04d9bed33ed1.png)

**Comment by YonatanKra** [comment]
Moved to VIV-903
