### ISSUE TITLE
[TextArea]: doesn't comply to host width (if set)

### ISSUE THREAD

**Issue by ObaidUr-Rahmaan** [Vonage/vivid-3#1080]
### Description

Resizing of TextArea causing some rendering problem to the outline (when selecting in the textarea)...

<img width="676" alt="image" src="https://user-images.githubusercontent.com/33055080/227219260-5f6aaad7-bdca-4b3b-84e7-0dedab5d14f6.png">

### Component(s) impacted

TextArea

### Browser

Chrome

### Vivid Web Components version

v3.4.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

Sigma

### CodeSandbox example

Not sure how to reproduce this way

### Steps to reproduce the issue (if applicable)

Only thing I show is the code:

```
                  <vwc-3-text-area
                    rows="5"
                    placeholder="Summary of the change in less than 100 chars"
                    :value="summary"
                    :disabled="isLoading"
                    maxlength=100
                    required="true"
                    class="w-full vvd-root"
                    @input="updateSummary">
                  </vwc-3-text-area>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
the text-area in the example has w-full which is width: 100% in tailwind. The text area is not fully stretched but the focus is.
**for devs:** the text-area wrapper div (`<div class="fieldset">`) is missing `width: 100% `

**Comment by YonatanKra** [comment]
@rachelbt , Is this issue blocked by VIV-904?

**Comment by rachelbt** [comment]
the issue moved to jira: https://jira.vonage.com/browse/VIV-905
