### ISSUE TITLE
[breadcrumbs] create new component

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#113]
refer https://shoelace.style/components/breadcrumb
to examine https://twitter.com/claviska/status/1478874761983840259?s=20

could suffix & prefix be defined by css alone? 

- [ ] Create breadcrumb item
- [ ] Create the breadcrumb "group"

**Comment by jshenkman** [comment]
Design `[here](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=8351%3A44289)`
