### ISSUE TITLE
[VwcBanner]: Wrong colors on Warning connotation

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid-3#1461]
### Description

When loading VwcBanner with connotation Warning and removable, the "close" icon is different color than text

![image](https://github.com/Vonage/vivid-3/assets/57232860/869228b2-0615-4a22-9e40-8ce8492ac5c3)

### Component(s) impacted

VwcBanner

### Vivid Web Components version

3.41.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://vivid.deno.dev/components/banner

### CodeSandbox example

https://vivid.deno.dev/components/banner

### Steps to reproduce the issue (if applicable)
```
<vwc-banner text="Here's some information that you may find important!" removable connotation="warning"></vwc-banner>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
@AyalaBu can you please have a look?

**Comment by AyalaBu** [comment]
I checked it in our API and it does appear to look this way
![Screenshot 2023-11-30 at 12 25 04](https://github.com/Vonage/vivid-3/assets/106529909/8bd1d990-cadd-451a-a604-d2829a5fb641)
I think that we do need to give it some attention

**Comment by rachelbt** [comment]
@dvelluto - I opened a ticket for this:
https://jira.vonage.com/browse/VIV-1431
I'm closing the github issue since we are tracking now Jira issues.
https://confluence.vonage.com/display/VIVID/How+to+raise+a+bug+for+the+Vivid+Library
