### ISSUE TITLE
[VwcDatePicker ]: allow to select time frames of hours/minutes/seconds like in Vivid-2

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid-3#1475]
### The problem

We need to bring old UIs written with vivid2 and Volta to vivid-3 but the DatePicker component is not supporting picking hours/minutes/seconds , just dates.

In vivid-2 it was possible to pick also time in format like 12.00 pm

### The solution

Provide a time picker component in vivid-3 that supports same functionalities as in vivid-2

### Application/website

VCC

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

https://dev.vivid.vonage.com/?path=/story/alpha-components-datepicker--time&args=enableTime:;noCalendar:

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
@dvelluto this is in progress:
https://jira.vonage.com/browse/VIV-972
you can follow the ticket :)
closing the git-hub issue.
