### ISSUE TITLE
[VWC-Card]: Laggy scrolling when multiple on screen

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid-3#1494]
### Description

when I have a list of cards on screen and I'm scrolling through them, I expect to have a pleasant experience, while right now the performances are quite low. With the performance tools of chrome if we record we see no issues in code, but a lot of GPU intensive tasks that slow down all. The most intensive task on page at this point is the "filter" applied on cards, used to do the drop-shadow.  
I recorded a possible point of failure and a possible improvement that would ease up the situation.
[laggy-vwc-cards.webm](https://github.com/Vonage/vivid-3/assets/57232860/05dc5303-6e42-40f1-b0e3-d2a86df7a969)

Possible solution:
use 
```
box-shadow: 0 2px 16px 0 rgba(0, 0, 0, 0.10), 0 8px 8px 0 rgba(0, 0, 0, 0.05), 0 4px 4px 0 rgba(0, 0, 0, 0.05);
```

instead of:
```
filter: drop-shadow(0px 2px 8px #0000001a) drop-shadow(0px 2px 4px #0000000d) drop-shadow(0px 4px 2px #0000000d);
```

### Component(s) impacted

vwc-card

### Vivid Web Components version

3.41.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

VCC

### CodeSandbox example

https://vivid.deno.dev/components/card

Live example with lot of cards
https://studious-parakeet-4b265650.pages.github.io/iframe.html?args=&id=components-cardsview--basic&viewMode=story

### Steps to reproduce the issue (if applicable)

https://vivid.deno.dev/components/card - on any example start to add cards so that the scroll bar are appearing, when there are few cards it feels fine, when you get over 20 it starts to lag (less than in the situation recorded in the video, because there are less components on the card)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by RichardHelm** [comment]
Hi Davide, thanks for the report! We're using JIRA now to track issues so I've created a ticket for this: https://jira.vonage.com/browse/VIV-1450

**Comment by dvelluto** [comment]
Hi @RichardHelm I see the jira task was closed because of the fix on tooltips but that was only one of the problems for performances. Please if you try the fix I'm suggesting on this issue, the performances will grow very much for our case and the look and feel won't be hurted. I attach a demo where I just switch from filter to box-shadow. In some cases we have 1000s of cards and in the recorded example there are 100s
[screen-capture (2).webm](https://github.com/Vonage/vivid-3/assets/57232860/93f83f91-ac23-49b0-a5e7-b4b497affacb)
