### ISSUE TITLE
[sidenav] new component

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#200]
- The vwc-sidenav would be commonly used inside the vwc-side-drawer.
- The vwc-sidenav will feature sidenav-item (link) and sidenav-menu (button expanding/collapsing list).
- The vwc-sidenav have to be accessible via keyboard

examples for side-nav component in other design systems:
- [Spectrum](https://opensource.adobe.com/spectrum-web-components/components/sidenav/)

**Comment by jshenkman** [comment]
Side navigation - [anatomy](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=11361%3A61632)

**Comment by yinonov** [comment]
## Focus management

Referencing the above libraries shows that roving index isn’t applied in all. There’s no significant take on whether focus management, thus keyboard navigation, should be applied to side navigation or not. should navigation be handled natively by tabbing?

some opinions suggest that a plain navigation does not need roving index but an [ARIA menu does](https://www.w3.org/TR/wai-aria-practices-1.2/#menu), and that adding such support is only relevant to menus.
ARIA menus are not for navigation, but for app actions.
here's a take on [flyout navigation](https://www.w3.org/WAI/tutorials/menus/flyout) vs [application menu](https://www.w3.org/WAI/tutorials/menus/application-menus).

**Comment by rinaok** [comment]
> ## Focus management
> Referencing the above libraries shows that roving index isn’t applied in all. There’s no significant take on whether focus management, thus keyboard navigation, should be applied to side navigation or not. should navigation be handled natively by tabbing?
> 
> Common opinions suggest that a plain navigation does not need roving index but an [ARIA menu does](https://www.w3.org/TR/wai-aria-practices-1.2/#menu), therefore adding such support is only relevant to menus. ARIA menus are not for navigation, but for app actions. here's a take on [flyout navigation](https://www.w3.org/WAI/tutorials/menus/flyout) vs [application menu](https://www.w3.org/WAI/tutorials/menus/application-menus).
> 
> [This issue](#200) is more relevant to a flyout design pattern (shared above), although it will only ascend vertically instead of a horizontal navigation flow.
> 
> Note that users can navigate through the list by tabbing, and can also **skip it** if it’s correctly identified as such (or a `<navigation>` [landmark](https://w3c.github.io/aria-practices/#aria_landmark). Screen readers all have a way to navigate by [landmarks](https://w3c.github.io/aria-practices/#aria_landmark), which give you a way to browse the page in a non-linear way. If the navigation is in a proper `<nav>`, that will make it skippable.
> 
> **A big caveat** here is that landmark navigation is quite an advanced skill for screen reader users. Designing for it alone is like designing for power users alone.
> 
> https://webaim.org/projects/screenreadersurvey9/#landmarks highlights some of this but WebAIM does skew toward the advanced user, so reality is probably even more dramatic
> 
> This complexity might be a reason for in-distinguished design pattern when referencing existing libraries and when it comes to focus management.
> 
> in opposed to side navigation, popup menu has clear visual indication of it being a composite widget. lack of such clear visual encapsulation may confuse sighted keyboard users trying to navigate side navigation by tabbing.
> 
> I suggest featuring opt-in / out to side navigation keyboard focus management
> 
> * authors may choose whether focus management should be enabled if navigation list is large and can become tedious to step through
> * **_enabling focus management should affect design to reflect clear visual indication of the side navigation component_**
> * alternatively document clear guidelines reflecting the above caveats when opting-in to focus management

@yinonov You suggest that focusing on the sidenav will affect the design. What do you want it to look like? Do you have an example for that?

@jshenkman @AyalaBu

**Comment by yinonov** [comment]
no.
focus management refer to what is tabbable and when keyboard focus management is integrated.
when no intervention, sidenav-items are tabbable. when there are, say, more than 12 items, tabbing through items can be tedious. in such scenarios, authors might want to opt-in to focus management to result in a tab stop on sidenav itself rather (than its items).
this means all nested items within sidenav will no longer be tabbable and will be focused by keyboard interaction (arrows etc').
that way users will be able to tab to sidenav and next tabbable sibling element following sidenav. without the need to go through all 12+ items

**Comment by AyalaBu** [comment]
Maybe we can consider a behavior like this:

https://atlassian.design/components/drawer/examples

but it doesn't have to be a modal,
and instead of a button maybe it can be a hamburger?

here it is similar:

https://codepen.io/illvart/pen/xLKqyR

https://codepen.io/butchewing/pen/PozMBoN

or maybe even something like this:

https://codepen.io/akshayvcsbim/pen/jwGxjj

What do you guys think?
