### ISSUE TITLE
[docs] encapsulate rendered code snippets within an Iframe

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#209]
rendered code snippets within the 11ty docs site should be encapsulated for various reasons -
- detachable pristine html 
- cases where component take control over document (e.g. side-drawer, top-bar, etc'.)

the plan is to dynamically create a src for iframe to render as if it was a real html page
see -
https://stackoverflow.com/questions/10418644/creating-an-iframe-with-given-html-dynamically

**Comment by yinonov** [comment]
does [codepen](https://codepen.io/) provide a way to dynamically embed pens (for pens that aren't hosted)?
