### ISSUE TITLE
[side-drawer] add blocking-elements when modal

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#272]
https://github.com/PolymerLabs/blocking-elements

**Comment by yinonov** [comment]
what if we wrap our aside and scrim in a presentational `div` element? then push that element to `blockingElements`?
will it workaround the issue?

**Comment by yinonov** [comment]
[tabbable](https://github.com/focus-trap/tabbable) is being used by [fast's dialog](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/dialog/dialog.spec.md) and might help in focus trapping
