### ISSUE TITLE
[colors]: missing design token

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#290]
this shade is missing in put tokens:
`--vvd-color-*connotation-name*-80`
it is needed for states: active.

**Comment by jshenkman** [comment]
These are the current tokens 
![Screen Shot 2022-04-04 at 12 44 56](https://user-images.githubusercontent.com/67224525/161518554-b79ff932-41d7-451d-b1f7-60a2897c3f2e.png)

For buttons states we use - 

- enabled - 60
- hover - 70
- selected -80

**Comment by jshenkman** [comment]
![Screen Shot 2022-04-04 at 13 39 53](https://user-images.githubusercontent.com/67224525/161527454-b5c62a36-2a25-40ae-8b8c-3a01a5255a94.png)

**Comment by jshenkman** [comment]
https://www.figma.com/file/t1AdIumwvp9NzLyLAgvBO4/design.tokens?node-id=1%3A212

Added the missing color to the design.tokens.scheme
