### ISSUE TITLE
Change banner's API

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#310]
- [x] Banner will be shown by default (no more `open` attribute)
- [x] `dismissible` will be replaced by `removable` and will remove the element from the DOM
- [x] The native `remove` method should be monkey patched (in the context of element only) in order to add the remove animation
- [ ] Make the `remove` monkeypatch a mixin `OnRemovalAnimationDelay` as a consumable pattern
- [x] Add a single action button/anchor
  - [x] `action-text` and `action-href` attributes
  - [x] Add anchor tag when button has `href`
  - [x] Add button that fires `vwc-banner:action` when clicked

**Comment by yinonov** [comment]
if `href` is set, action button should convert to anchor (`text-anchor`?).
meaning scoped event won't fire on click?
