### ISSUE TITLE
Should we have buffered state for progress?

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#319]
### Open discussion
@yinonov @rachelbt @jshenkman @rinaok 

Currently `vivid-2` has `buffered` state (taken from Material).
I do not believe this was adopted in Vonage and it is no a requirement in Figma.
Should we consider supporting it to `vivid-3` progress?

**Comment by yinonov** [comment]
Important to note it was presented in storybook

**Comment by rachelbt** [comment]
this thingy?
![image](https://user-images.githubusercontent.com/7512792/163704898-925272fa-18df-4280-a0f4-baecab25a7d0.png)

It is so strange...
