### ISSUE TITLE
[Accordion-Item]: Dense

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#338]
### The problem

Does the accordion item need a dense attribute?

What should we call it?

### The solution

.

### Application/website

.

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
as @jshenkman described the definition is not styling the size of the accordion item but control its inner parts and result in a smaller proportions.

proposing dense / condensed?

**Comment by rinaok** [comment]
https://github.com/microsoft/fast/issues/5510

**Comment by rinaok** [comment]
@yinonov @jshenkman We have a `mini` attribute inside fab. Is it also dense? 
https://dev.vivid.vonage.com/?path=/story/alpha-components-fab--mini&args=mini:;icon:store

**Comment by rinaok** [comment]
@yinonov Until then, I won't add the mini. ok?

**Comment by yinonov** [comment]
> @yinonov Until then, I won't add the mini. ok?

Yes exactly thanks
