### ISSUE TITLE
[State] new State component

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid-3#36]
In Vivid-3 we are not using the material ripple component for presenting states.
States component will replace it.
Buttons are the first component that we will be using it.
out states:

- disabled
- hover
- active (when pressing)

Primary color will have an exception behavior for the hover & active states. While all the connotation are getting darker primary start at its darkest hens is getting lighter.

![image](https://user-images.githubusercontent.com/7512792/149968108-6051f511-c643-4287-9d89-3831f888f910.png)

The ghost Primary colors for the states will be the default states.

We are ditching the "ripple" effect. Other Animation is in consideration.

*Focus state which is a different Component - will be presented only with keyboard navigation.

**Comment by jshenkman** [comment]
Currently, our buttons extend Material's state system (using ripple).
We want to move away from this solution and implement our own states, using colors from the palette (design tokens) 
Including - Button, Icon Button, and Icon Button Toggle.

You can find the states [here](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=1915%3A1510)

**Comment by yinonov** [comment]
the **_state indicator_** component should be unaware of its containing component.
meaning it does not know anything about _connotation_ or _appearance_.

suggesting to have a single behavior for all and if need to have more customization per permutation, we can expose css variables to allow it
