### ISSUE TITLE
Text field

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#372]

**Comment by jshenkman** [comment]
https://www.figma.com/file/BZFhGux6k3q462BSmTPYeX/Exploration?node-id=808%3A184939

**Comment by rachelbt** [comment]
If there's only label on the top of the input - there's a problem with ghost textfield inside action-group:
![image](https://user-images.githubusercontent.com/7512792/169698932-4d07b93e-8383-4b1e-8390-224d0059c24f.png)
