### ISSUE TITLE
[progress]: component rounded shape doesn't work

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#385]
### Description

 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/15140652/168443395-b81bd39a-9b40-4dd8-8c23-7b029ab637a5.png">

progress should support rounded shape and apply to bar as well
as in [vivid < 3 storybook](https://vivid.vonage.com/?path=/story/components-linear-progress--default&args=progress:0.25;buffer:1)
<img width="510" alt="image" src="https://user-images.githubusercontent.com/15140652/168443440-45fdb283-9eb5-4ded-b1f8-539a627787f6.png">

### Component(s) impacted

progress

### Vivid Web Components version

whatever

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

null

### CodeSandbox example

no need

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
@YonatanKra noticed this?

**Comment by rachelbt** [comment]
@YonatanKra I'll take it if its OK by you - its CSS :)

**Comment by YonatanKra** [comment]
@rachelbt feel free. Ill review cause I have a suspicion why this happened and I'd like to check it to make the ui tests better than ever 😀
