### ISSUE TITLE
[TOOLTIP]: Accessibility

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#435]
### The problem

**Behavior**

- A Tooltip must have a focusable, interactive trigger
- A Tooltip should show on mouse hover and keyboard focus
- A Tooltip must not contain focusable or interactive content
- Tabbing to the element displays the tooltip
- Escape hides the tooltip
- Focus always stays on the trigger element

**Markup**
- Tooltip needs **role="tooltip"**
- Trigger Element needs **aria-describedby** set to the id of the tooltip

### The solution

To remove the click listener from the trigger and to add the click, hover, and focus listeners to be on the template by default. 

### Application/website

vivid

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
This should probably be described under a11y section in tooltip docs.

popover might be where this will actually be implemented

**Comment by rachelbt** [comment]
I think we can implement this one:
Tooltip needs role="tooltip"

**Comment by rinaok** [comment]
@rachelbt Yes, it's missing
