### ISSUE TITLE
[Accordion]: Behavior

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#436]
### The problem

**Up and Down arrows**: when focused on a section header should navigate to the next/previous header.

This should not change the state of the section (if the section is hidden, it stays hidden).

### The solution

.

### Application/website

vivid

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
This practice is called roving and should be implemented in several components where tab navigation is tedious. When there are just a few accordion items this might not be needed and even worsen an experience.
This might be an opt-in/out feature.

Look for roving ux library

**Comment by yinonov** [comment]
Accordion items are landmarks containing headings and might not require additional programmatic focus management
