### ISSUE TITLE
Textfield Completions

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#437]
- [x] #439
- [ ] Inputmode
- [x] #450
- [x] #449
- [x] Label grayed out in disabled state
- [x] #446
- [x] #445
- [x] #447
- [x] #448

**Comment by yinonov** [comment]
[enterkeyhint](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint)? missing in foundation
