### ISSUE TITLE
[text-field]: Size API - default width on the host, host width controls the input's width

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#449]
Usage of `size` attribute to set the size of the textfield.

**Comment by rachelbt** [comment]
@yinonov , @YonatanKra 
usually when we are using attributes its for pre-defined members (like connotation, shape density...).
Are we doing this in the text-field?
why not change the width with css-variable or simply setting default width on host and user can change it with style on component?

**Comment by YonatanKra** [comment]
> @yinonov , @YonatanKra 
> usually when we are using attributes its for pre-defined members (like connotation, shape density...).
> Are we doing this in the text-field?
> why not change the width with css-variable or simply setting default width on host and user can change it with style on component?

@rachelbt 

https://www.w3schools.com/tags/att_input_size.asp

**Comment by rachelbt** [comment]
@yinonov 
I've set in the linked PR 20ch default inline-size as we talked.
I've opened an issue for using the [size API](https://github.com/Vonage/vivid-3/issues/461)
