### ISSUE TITLE
[text-field]: a11y cover

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#450]
https://www.ovl.design/text/inclusive-inputs/

- [ ] Add `aria-invalid` when the input is invalid

**Comment by YonatanKra** [comment]
@yinonov @rachelbt 
Do we autofill `autocomplete` value in case it is not defined by the user (autofill it with the `name` attribute value)?

**Comment by YonatanKra** [comment]
@yinonov @rachelbt 
Should we set `aria-describedby` with our helper text by default if it exists?

**Comment by jshenkman** [comment]
> @jshenkman How do we mark a field as `required`?

The common representation is to add an asterisk * to the label of the field 
For example - 
![Screen Shot 2022-06-14 at 17 03 40](https://user-images.githubusercontent.com/67224525/173596606-251e4ec9-88a7-460d-bd1c-114ebed84502.png)

In our text field 
![Screen Shot 2022-06-14 at 17 05 57](https://user-images.githubusercontent.com/67224525/173597095-2ca2f08c-a0b8-4c85-b64a-9ccb4b4e34e6.png)
