### ISSUE TITLE
Consider semantic style naming

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#479]
maybe the intent is wrong. maybe it should be adding `user-not-valid` class to be completely correct

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/pull/454#discussion_r901054467_

**Comment by yinonov** [comment]
Follow @YonatanKra - @yinonov discussion

https://vonage.slack.com/archives/D016CUWT3LK/p1655911496259109

**Comment by yinonov** [comment]
@YonatanKra close?

**Comment by yinonov** [comment]
@YonatanKra reopen if need
