### ISSUE TITLE
Reassess top text terminology according to context

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#480]
I think we should reconsider the way we define top text hierarchy. given that _heading_ should probably introduce an actual heading element (Hx) in template.

certain cases, like note, where Hx isn't wrapping the text, title might be a better member name

<img width="219" alt="image" src="https://user-images.githubusercontent.com/15140652/175009675-91fa1b81-3b99-45c5-a97d-33bb58c7330b.png">

@rachelbt FYI. should we open this up?

__Originally posted by @yinonov in https://github.com/Vonage/vivid-3/pull/404#discussion_r903578485__

**Comment by rachelbt** [comment]
@yinonov  As we talked today: 
- if there's an HTML H tag than we will name it Heading
- if there's no HTML H tag (e/g/ Card, Note) than we will use: 
-- headline
-- subtitle

**Comment by yinonov** [comment]
> @yinonov As we talked today:
> 
> * if there's an HTML H tag than we will name it Heading
> * if there's no HTML H tag (e.g. Card, Note) than we will use:
>   -- headline
>   -- subtitle

what if we have more hierarchy?

**Comment by rachelbt** [comment]
> > @yinonov As we talked today:
> > 
> > * if there's an HTML H tag than we will name it Heading
> > * if there's no HTML H tag (e.g. Card, Note) than we will use:
> >   -- headline
> >   -- subtitle
> 
> what if we have more hierarchy?

Such as?
All I can think of from our components is "text"

**Comment by yinonov** [comment]
> > > @yinonov As we talked today:
> 
> > > 
> 
> > > * if there's an HTML H tag than we will name it Heading
> 
> > > * if there's no HTML H tag (e.g. Card, Note) than we will use:
> 
> > >   -- headline
> 
> > >   -- subtitle
> 
> > 
> 
> > what if we have more hierarchy?
> 
> 
> 
> Such as?
> 
> All I can think of from our components is "text" 

Ok hope that would be it
