### ISSUE TITLE
[breadcrumb] should reflect a navigation role

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#487]
notice, due to vivid avoiding the practice of mutating host, and rather utilize it as service, we skip the _template_ syntax / tag causing the breadcrumb to reflect only as list role

https://github.com/microsoft/fast/blob/0e94e9cdecc82986af91d94713df313f7bdca8aa/packages/web-components/fast-foundation/src/breadcrumb/breadcrumb.template.ts#L14

we should implement such role as a wrapper in template

**Comment by yinonov** [comment]
@YonatanKra 👆

**Comment by yinonov** [comment]
I believe automated checks would have thrown on that
see
https://github.com/Vonage/vivid-3/blob/2422ecd643bce34929c16ef02e5e80a8cf73c1a2/libs/components/src/lib/calendar/calendar.spec.ts#L312-L327

**Comment by YonatanKra** [comment]
> I believe automated checks would have thrown on that see
> 
> https://github.com/Vonage/vivid-3/blob/2422ecd643bce34929c16ef02e5e80a8cf73c1a2/libs/components/src/lib/calendar/calendar.spec.ts#L312-L327

No it does not:
![image](https://user-images.githubusercontent.com/6459899/177337996-2155d3db-500a-4951-a29d-c842bffc6daa.png)
