### ISSUE TITLE
[docs]: change icon in open side drawer documentation

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#496]
Open/Close side-drawer functionality is not clearly understood. I propose to change the hamburger icon to X icon when the component is closed, or think about a different functionality solution altogether in order to supply a better user experience. 

I've checked a few other design systems, and in none of the "open menu" icon often represented by a hamburger icon was **in the same line** with the side menu, and used to **move aside** when the menu was opened.
For some examples you can check the functionality in your gmail, or look at these references:

https://docs.microsoft.com/en-us/windows/apps/design/basics/navigation-basics
https://www.patternfly.org/v4/components/navigation/design-guidelines
https://designsystem.backbase.com/v2/web-components/layouts-and-navigation/design

Note: I would prefer the hamburger icon to change to X icon like in these references (but after my little research it bothers me less that hamburger icon that moves aside when the menu opens):

https://codepen.io/choogoor/pen/yJLOgp
https://codepen.io/aderaaij/pen/pgNxwY
https://codepen.io/gustavomodena/pen/adZgWK

It doesn't have to be with the beautiful animations as seen in these references, but I think that an icon change delivers the message better.

Also, there were other examples of side menu functionality that i have found:

https://designsystem.backbase.com/v2/web-components/layouts-and-navigation/design

p.s. scroll to the "Small screen with collapsed menu"

https://vmware.github.io/clarity/documentation/v0.12/vertical-nav/basic-structure/charmander
Maybe we can use a "collapse/expand" icons from our design system, and it can clearly deliver the message. 

Maybe instead of hamburger icon it can be an arrow that functions as open/close component, maybe something like this:

https://codepen.io/simoberny/pen/vNYavm

Same functionality exists in Dell design system:

https://www.delldesignsystem.com/components/side-navigation/

![Component-closed](https://user-images.githubusercontent.com/106529909/175892600-f5dd17e4-ce08-4a8b-97e9-7d092f9f73fe.png)
![Component-open](https://user-images.githubusercontent.com/106529909/175892608-26a419b6-f04d-4075-bf0f-0f734ff78b4a.png)

 I would love to know your thoughts about this issue

**Comment by yinonov** [comment]
here's a question to tackle, a modal aside (featured in side-drawer) is currently only scrims the main app content and doesn't block the header as well. is this a correct implementation of a modal? it's a conflict of stacking context vs inert of elements

**Comment by rinaok** [comment]
@AyalaBu Current design hides the last button inside the sidenav.
<img width="290" alt="Screen Shot 2022-07-11 at 13 50 18" src="https://user-images.githubusercontent.com/10883919/178248485-e62a226c-7b04-49fe-b99a-951d28ed6ce3.png">

**Comment by rinaok** [comment]
@AyalaBu Can we close this issue?
