### ISSUE TITLE
Consolidate position terminology

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#510]
Our goal is to consolidate the terminology used to describe the position of an element anchored to another.

popup features the *corner* terminology -
https://github.com/Vonage/vivid-3/tree/main/libs/components/src/lib/popup#corner

The [Microsoft explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md#declaring-preferred-anchored-position-with-fallbacks) introduces a concept of "position-set" in the context of *declaring preferred anchored position, with fallbacks*.
This might still be early in the process of being standardized, and it's not clear if it will be implemented in the future. it also seems to be a bit of a misnomer, as it's not a set of positions, but a set of fallbacks.

Vivid popup doesn't support such complex positioning.

Side drawer might deviate from the complexity presented here as it only allows 2 options; *left* and *right* (or *start* and *end*). A boolean member might be enough for its purpose.

**Comment by rinaok** [comment]
Floating-ui calls it **Placement** instead of **Corner**.  https://floating-ui.com/docs/computePosition#placement

**Comment by yinonov** [comment]
placement is an option. `position` is probably more close to the explainer's `position set `

**Comment by rinaok** [comment]
Regarding the Side-Drawer, we have **icon-trailing** so I think that the name you suggested (**trailing**) can be a good fit.

**Comment by rinaok** [comment]
> placement is an option. `position` is probably more close to the explainer's `position set `

**Position** reminds me of the position property (static, relative, fixed, absolute or sticky). Idk if it's a good name for this purpose.

**Comment by yinonov** [comment]
has not progressed lately but might help with guidance
https://github.com/w3c/csswg-drafts/issues/5952

**Comment by yinonov** [comment]
I foresee a similar debate starting here https://github.com/microsoft/fast/issues/6185#issuecomment-1176341634

**Comment by rinaok** [comment]
> @yinonov @rinaok @rachelbt Are we going with `placement` then?

@YonatanKra  At the beginning, it was *Placement*. vwc-menu and vwc-dropdown have *Corner*, and we wanted consistency. It might be better to change it to Placement in all components.

**Comment by YonatanKra** [comment]
@rinaok 
Was it decided then? I can't see a decision in this discussion.  Any `vivid-3` component using `placement`?
I see `popup` and `tooltip` are using it (probably because of `floating-ui`).
Maybe we can just decide on placement.

**Comment by rinaok** [comment]
@yinonov What do you think? Should we change "corner" to 'placement"?

**Comment by yinonov** [comment]
> @yinonov What do you think? Should we change "corner" to 'placement"?

Agree 👍
