### ISSUE TITLE
[styles] typography as css

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#517]
Vivid features the `vwc-text` element to integrated a predefined set of font faces.
This element provides an accurate way to control font faces style in accordance to html semantics.

Problem is its interface is cumbersome and not always easy to work with in systems where html isn't controlled by authors (e.g. markdown to html)

As vivid-3 introduces styles in its core, consumers can opt-in and include typography css right out of the vivid components library

- ensure typography styles only apply when a global class exist (e.g. `.vivid-page`)
- if possible migrate `px` to `rem`

**Comment by rachelbt** [comment]
consider using this to calculate font for responsiveness:
https://min-max-calculator.9elements.com/
