### ISSUE TITLE
[docs] include meta tags for social media sharing

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#518]
sharing vivid in rich context posts shows a poor social banner.

Add meta tags to engage users

<img width="294" alt="image" src="https://user-images.githubusercontent.com/15140652/177560098-ecbb172c-4c8d-43d0-916c-c8f52a22a720.png">

**Comment by rachelbt** [comment]
reference: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by jshenkman** [comment]
<img width="790" alt="Screen Shot 2022-07-12 at 15 08 59" src="https://user-images.githubusercontent.com/67224525/178486415-00b3bb35-5643-4c92-bf9d-eea8d4bf20cc.png">
<img width="694" alt="Screen Shot 2022-07-12 at 15 09 47" src="https://user-images.githubusercontent.com/67224525/178486511-7ae5afb5-8c5f-4b00-bfa2-03a887669cc6.png">

One of these? what format do you need it? png or SVG?

**Comment by rachelbt** [comment]
> <img alt="Screen Shot 2022-07-12 at 15 08 59" width="790" src="https://user-images.githubusercontent.com/67224525/178486415-00b3bb35-5643-4c92-bf9d-eea8d4bf20cc.png">
> 
> <img alt="Screen Shot 2022-07-12 at 15 09 47" width="694" src="https://user-images.githubusercontent.com/67224525/178486511-7ae5afb5-8c5f-4b00-bfa2-03a887669cc6.png">
> 
> One of these? what format do you need it? png or SVG?

PNG please and not svg.
About the design - I think that we can add the text - web components like you added in Vivid-next doocumentation.
Also, maybe the image can be more dominant with a dar bg or ant color or pattern.
this is how it will look in the end:
![image](https://user-images.githubusercontent.com/7512792/178690329-29e86f00-0afb-4f60-9e9c-07f185998ba6.png)
![image](https://user-images.githubusercontent.com/7512792/178690390-ff6e7416-6c78-4f76-babd-c2c0d6d4b4a8.png)
sample from a link that was shared:
![image](https://user-images.githubusercontent.com/7512792/178690509-ca9d75cc-a0a2-438f-9f50-c13e2e6290e7.png)

**Comment by jshenkman** [comment]
<img width="1104" alt="Screen Shot 2022-07-14 at 15 22 21" src="https://user-images.githubusercontent.com/67224525/178981232-629d1827-b864-42fd-a2cb-77264d9ac002.png">

Or this style?

**Comment by rachelbt** [comment]
> <img alt="Screen Shot 2022-07-14 at 15 22 21" width="1104" src="https://user-images.githubusercontent.com/67224525/178981232-629d1827-b864-42fd-a2cb-77264d9ac002.png">
> 
> Or this style?

I like this one :)
