### ISSUE TITLE
[Avatar] create new component

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#530]

**Comment by rachelbt** [comment]
@jshenkman , @AyalaBu 
Can you please add design? Thanks

**Comment by yinonov** [comment]
use case examples were raised at https://jira.vonage.com/browse/VIV-801

**Comment by rachelbt** [comment]
> use case examples were raised at https://jira.vonage.com/browse/VIV-801

@jshenkman, @AyalaBu 

- Do we have filed + outlined appearance?
- Do we have different connotation or only accent?
- Do we have sizes?
- Are we providing a default icon?

**Comment by yinonov** [comment]
I imagine size should have parity with button density as avatar might be actionable, reside next to icon buttons and align with density baseline at least

**Comment by AyalaBu** [comment]
Actually in some design systems that I checked there are multiple avatar
sizes,
And it is something that we should consider to create

**Comment by AyalaBu** [comment]
Avatar can now enter production.

This is the link:
[](https://www.figma.com/file/onZE3utmYX80geUE16xOgc/Avatars!?node-id=21%3A80148)

The avatar component that needs development is **Light/Avatar**

**It includes:**
1. Avatar density: -2 | -1 | 0 | 1 | 2 | 3
2. Avatar connotation: CTA, Accent
3. Avatar content: icon, initials, picture
4. Avatar shape: rounded, pill
5. Avatar type: filled, outline, ghost

Good luck!

**Comment by rachelbt** [comment]
> Avatar can now enter production.
> 
> This is the link: https://www.figma.com/file/onZE3utmYX80geUE16xOgc/Avatars!?node-id=21%3A80148
> 
> The avatar component that needs development is **Light/Avatar**
> 
> **It includes:**
> 
> 1. Avatar density: -2 | -1 | 0 | 1 | 2 | 3
> 2. Avatar connotation: CTA, Accent
> 3. Avatar content: icon, initials, picture
> 4. Avatar shape: rounded, pill
> 5. Avatar type: filled, outline, ghost
> 
> Good luck!

Density - 3 sizes - same as buttons.
Density block is not included in this round. It has its own [issue ](https://github.com/Vonage/vivid-3/issues/645).
Acronyms  also not in this scope. [Acronyms issue](https://github.com/Vonage/vivid-3/issues/613).

@AyalaBu you can do VQA here:
https://vivid-mk8e95e79qb0.deno.dev/components/avatar

**Comment by AyalaBu** [comment]
Avatars look great!
