### ISSUE TITLE
[Snackbar / Banner / Toast / Alert] - consolidate and remove redundant features

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#532]
## Banner

Addresses a scenario where page notifies a user of an important message in an intrusive manner.

Most UX design name the equivalent vivid banner as banner, some call it toast 🤷‍♂️. Most use the role `alert` internally. some assign log as role

- [w3c school](https://www.w3schools.com/howto/howto_js_alert.asp)
- [w3 aria](https://www.w3.org/WAI/ARIA/apg/example-index/alert/alert)
- [nord](https://nordhealth.design/components/banner/)
- [spectrum](https://opensource.adobe.com/spectrum-web-components/components/toast/)
- [Atlassian](https://atlassian.design/components/banner/examples)
- [Carbon inline](https://web-components.carbondesignsystem.com/?path=/story/components-notifications--inline)
- [Carbon Toast](https://web-components.carbondesignsystem.com/?path=/story/components-notifications--toast)

- [ ] Banner - consider renaming to alert?
- [ ] Banner - default to role

A dismissible element requires programmatic handling of user alert and disruption
As Banner is no longer a dismissible element, rather has natural flow display, it might not need that programmatic handling

- [ ] Banner - remove programmatic handling of user alert

## Snackbar

Addresses a scenario where a page notifies a user of a system occurrences and often requires immediate user attention

Overlaps with Toast

- [ ] Snackbar - consider renaming to log

Some library maintainers allow multiple stacked instances

- [ ] Snackbar - consider allowing stacked instances

**Comment by olaf-k** [comment]
reopening as we're still missing at one or several component(s).

the Carbon summary @jshenkman linked is a good document to compare to. so here's an attempt:

- **banner**: used for persistent app-wide notifications. generally presented on top of content. already exists in Vivid.
- **inline notifications**: mostly used for task-related notifications (forms most of the time?). presented close to related items. does not exist in Vivid.
- **toasts**: used for ephemeral app-wide notifications. generally showed in a corner above all other content. does not exist in Vivid.

notes:

- our banner displays only centered content atm > should this be customizable? it is also optionally actionable > should it be?
- inline notifications seem to just be our current banner displayed next to task items.
- toasts exist in Vivid 2 as snackbars. the most significant difference being that they appear at the bottom and are not stackable.

**Comment by AyalaBu** [comment]
@rinaok 
The design is finished:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=21271%3A142119&t=DTrdMW2piZjbOokz-1

The component still needs to be migrated.

**Comment by AyalaBu** [comment]
The issue was moved to JIRA:
https://jira.vonage.com/browse/VIV-1009
