### ISSUE TITLE
Fabs and buttons has focus ring in mobile when pressed

### ISSUE THREAD

**Issue by TamirVonage** [Vonage/vivid-3#539]
### Description

Fabs and buttons has focus ring in mobile when pressed

### Component(s) impacted

buttons, fabs probably more things

### Vivid Web Components version

3.0.0-next.30

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Chat widget

### CodeSandbox example

none

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by TamirVonage** [comment]
It also happens on iOS. I don't think it's expected from a design perspective.
Do you want to ask Joella?

**Comment by rinaok** [comment]
@TamirVonage Can you add a screenshot? I have an iPhone and can't see the focus ring.

**Comment by TamirVonage** [comment]
![Screen Shot 2022-07-18 at 12 15 22](https://user-images.githubusercontent.com/54806024/179480987-a33f869a-5420-495f-af5e-2c51288f39bb.png)

**Comment by yinonov** [comment]
this is as designed and expected. where `:not(:focus-visible)`.
please reopen if need
