### ISSUE TITLE
[Header]: z-index in Safari & mobile ios

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#541]
### Description

https://user-images.githubusercontent.com/10883919/178994074-61085bd7-c9e5-44c6-ae85-4cf4e39f8670.MP4

### Component(s) impacted

header

### Vivid Web Components version

vivid-next

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

vivid

### CodeSandbox example

.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
Hmm that's new

**Comment by rachelbt** [comment]
this is because of the `z-index:0` that was given to `vwc-header#header-main.`
we can change it to 1 and give the side-drawer `z-index:2`.
this will solve it.

**Comment by rinaok** [comment]
@rachelbt I see that you closed the fix PR

**Comment by rachelbt** [comment]
> @rachelbt I see that you closed the fix PR

Yes, we changed the layout structure

**Comment by rinaok** [comment]
> > @rachelbt I see that you closed the fix PR
> 
> Yes, we changed the layout structure: #560

@yinonov @rachelbt I still see the problem on my phone so I don't know if we should close this issue or not.

**Comment by rachelbt** [comment]
@rinaok check now - its OK:
https://vivid.deno.dev/components/button
