### ISSUE TITLE
Add top-position to dialog 

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#544]
After we [Consolidate position terminology](https://github.com/Vonage/vivid-3/issues/510)

For the sake of agility, we can position the dialog in center and merge this PR, then right after create a PR for the top positioning

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/issues/505#issuecomment-1179695260_

**Comment by yinonov** [comment]
Dialog, not set as _modaldialog_, is positioned at the top.
There could be requests coming in for modal dialog to be positioned but as this difference in native dialog behaviour is already applied, we need to understand the reasoning behind this condition. Closing for now.
Please reopen when researched thoroughly
