### ISSUE TITLE
[Side-nav] Expand/collapse behaviour

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid-3#551]
Lately, we changed the side-nav expand/collapse behavior to a FAB in the bottom left of the page. I am not satisfied with this solution as the position of the button gives it a low hierarchy in the layout of the page, It overlaps the last item of the navigation list and it's not a common behavior or best practice for this type of action. 

![Image](https://user-images.githubusercontent.com/67224525/179491847-9ec9014d-69a5-48f6-a1f2-e095ca0d36b0.png)

A FAB should perform a constructive action such as create, share, or explore and shouldn't be used for minor, layout, overflow, unclear, or destructive actions, such as: Trash, Alerts, or controls better suited to a toolbar. 

Examples of FABs can be chat, help, share, favorite, and new usually placed in the bottom right of the UI. 

You can find [here](https://www.figma.com/file/QG5hvuw5qsfS0XYMVJ6V3L/Vivid-UI-Kit---Exploration?node-id=3776%3A41937) examples of all side-nav in Vonage's products and their behavior

And [new recommended ](https://www.figma.com/file/QG5hvuw5qsfS0XYMVJ6V3L/Vivid-UI-Kit---Exploration?node-id=3769%3A41347)behaviors we should support in our component. 

We should also change the behavior [here in our docs](https://vivid.deno.dev/components/side-drawer#application-content-offset) to the new behavior supporting the following use-cases: 
1. Primary header + secondary drawer
2. Primary drawer + secondary header
3. Drawer as modal (shown as the responsive use case) 
4. Collapse drawer to navigation rail (support in the future?)

**Comment by rachelbt** [comment]
@jshenkman can you p[lease varify:
https://vivid-5k76ffz5m4m0.deno.dev/

**Comment by jshenkman** [comment]
> @jshenkman can you p[lease verify: https://vivid-5k76ffz5m4m0.deno.dev/

LOVE IT! Looks amazing! also on mobile! 😍
thanks 🙏🏻
