### ISSUE TITLE
Header in Vivid-3 docs

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid-3#552]
Change Header + Side-nav in our current docs:
1. move Vivid logo from the side-nav to the header - when the logo is in the side-nav and we collapse the sid-nav we "lose" our Vivid logo. We want the logo to always be displayed 😍
2. Change the logo to 
![Image](https://user-images.githubusercontent.com/67224525/179494065-fc47fafd-d32f-44e9-ac97-f5fd62facfec.png)
OR back to this 
![Image](https://user-images.githubusercontent.com/67224525/179494101-74d0ad97-29e2-4f77-85d2-0901b9bcb6ca.png)
(Your choice @yinonov @rachelbt)

3. Make the logo a shortcut to the homepage? I notice currently the logo is not interactable so if we navigate to a different page we have no access back to the homepage.

**Comment by jshenkman** [comment]
Notice this ticket as well https://github.com/Vonage/vivid-3/issues/496

Once we fix the side nav I would want the doc to look something like this 
![Image](https://user-images.githubusercontent.com/67224525/179494738-e12c88bb-96f0-497d-a732-fb9df5fd807f.png)

Or this (depending on the logo) 
![Image](https://user-images.githubusercontent.com/67224525/179494940-3a896b2e-29df-48da-ad5b-d32ff6e05151.png)

**Comment by rachelbt** [comment]
@jshenkman 
for Visual QA:
- now the header is starched above the side-drawer
- in main page: added the grey in the first part
- in all component page - added bg to the component name. (didn't add the image - leaving it to another PR).
- please check both desktop & mobile
- there might be some breaking in mobile due to the typography and lone names of the components member (e.g. Accessibility).
Thanks

**Comment by jshenkman** [comment]
Oh, one more thing - can we have a different page template/layout for component pages and design system pages?
In these design system/foundation pages I made nicer graphics like this for color

<img width="1011" alt="Screen Shot 2022-07-28 at 11 04 36" src="https://user-images.githubusercontent.com/67224525/181454385-3240ce30-a5bb-46fa-88fb-77fc3bce52f5.png">

And also the typography on the color page is too big, in the first section. So I think we should deal with it separately?

**Comment by rachelbt** [comment]
> @rachelbt looks amazing!!!
> 
> * Header is perfect. logo size and position is great.
> * For now, it's great. I would like to change the graphics instead of Vivid logo something else, maybe like these clouds - but we can deal with it in another PR :)
> 
> <img alt="Screen Shot 2022-07-28 at 10 53 19" width="665" src="https://user-images.githubusercontent.com/67224525/181451998-32428d7c-24b3-4814-a775-ef928670bd48.png">
> 
> * Love the colored strip! But I think it should be one shade darker so instead of purple-500 purple-600 (in current tokens I think its purple-70 #871EFF)
>   In general, I would like the strip to be a bit bigger (the height) and contain also the page's tabs and maybe a short component description like this -
> 
> <img alt="Screen Shot 2022-07-28 at 10 59 39" width="955" src="https://user-images.githubusercontent.com/67224525/181453385-d100e211-ab55-4e39-8a77-2104d60dd982.png">
> 
> * Looks good also on mobile.
>   Great job looks amazing!!!!

I changed the color.
Adding images in in process we will add the decorative images after that will be done in a separate PR.
Different template is for another PR
