### ISSUE TITLE
Set the html height outside the code snippet

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#558]
I think we need to solve this. We said users need only copy paste, but this thing is not part of the copy-pasting stuff.

_Originally posted by @YonatanKra in https://github.com/Vonage/vivid-3/pull/556#discussion_r926329819_

**Comment by rachelbt** [comment]
we are using in several places style on the HTML for making the iftame block-size like this:

html preview
<style>
  html { 
    block-size: 200px; 
  html { /* for demo purposes */ 
....
