### ISSUE TITLE
[note] implement re-design

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#581]

**Comment by yinonov** [comment]
@AyalaBu can you please share the new design?

**Comment by jshenkman** [comment]
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=10968%3A61965

Here it is :)

**Comment by rachelbt** [comment]
@jshenkman @yinonov @AyalaBu 
We are implementing it also in Vivid-2? Are we over-riding the current design with the new one?

**Comment by jshenkman** [comment]
> @jshenkman @yinonov @AyalaBu We are implementing it also in Vivid-2? Are we over-riding the current design with the new one?

It will be amazing if we implement also in vivid-2 but it's up to @yinons prioritization :) 
And regarding overriding, not sure.. should we keep a legacy mode? I think in Vivid-3 we don't need legacy mode cuz no one started using it, but in Vivid-2 maybe (same as snack-bar?)

**Comment by rachelbt** [comment]
I started implementing the new design in [vivid-2](https://github.com/Vonage/vivid/issues/1337). 
The colors in the new design looks like vivid-2 `layout-soft` or vivid-next `appearance='subtle'` but they are not.
The background of the note is `--vvd-color-connotation-10` where in badge (where we have soft + subtle) its `--vvd-color-connotation-20`.
The outline and icon color is `--vvd-color-connotation-70` and not `--vvd-color-connotation`.
I understand that the badge is small and needs "stronger" background, but we need to decide about the color mapping.
I opened a PR with "soft" colors in the note in vivid-2:
https://github.com/Vonage/vivid/pull/1338

**Comment by AyalaBu** [comment]
@yinonov 
VBC designers want to use the note component,
but since we were in the process with checking the appearance models,
and note is the only component that looks different,
we didn't completely decide how to treat it.
Perhaps the time for that is now. What do you think?

**Comment by yinonov** [comment]
yes. please start the exploration file in Figma and reflect the issues we faced and the reasons for the push back. then find a suitable solution in design that follow vivid design patterns and principals

**Comment by AyalaBu** [comment]
@yinonov 
I edited the "Feedback" page in the "Exploration" Figma file:

https://www.figma.com/file/BZFhGux6k3q462BSmTPYeX/Exploration?node-id=2183%3A256622

and wrote in the Slack that I would appreciate if designers would take a look and vote,
so that we can decide on how to handle the note appearance issue.

As far as I'm aware of there is no issue in JIRA,
so I only edited the issue I opened in GitHub:

https://github.com/Vonage/vivid-3/issues/729
