### ISSUE TITLE
FAST form association does not work with required and form submit

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid-3#585]
Note there's an issue with FAST's form association - you cannot use `required` with form submit.

https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

Reproduction with FAST: 
https://codesandbox.io/s/quizzical-cdn-3wrl4e?file=/src/index.js

FAST started tracking this issue:
https://github.com/microsoft/fast/issues/5678

**Comment by yinonov** [comment]
Can we try disabling focus delegation for the time being. It's an UX enhancement we can live without until fixed

https://github.com/microsoft/fast/issues/5678#issuecomment-1211046234

**Comment by YonatanKra** [comment]
We already solved it in our own repo.
We even have a test that makes sure it works (both e2e as well as unit tests).
