### ISSUE TITLE
[sidenav-item]: Icon only

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#608]
### Description

When there is only an icon in sidenav-item, the hover and the active appearances are with the width of the icon:

https://vivid.deno.dev/components/sidenav-item#icon

![Screen Shot 2022-08-08 at 16 46 48](https://user-images.githubusercontent.com/10883919/183433088-979c92f4-ba10-45c9-8efc-41c38f0411f8.png)

it should be like that:

![Screen Shot 2022-08-08 at 16 47 01](https://user-images.githubusercontent.com/10883919/183433136-647dda43-cdff-48bc-8df5-b4fa0d61a39d.png)

### Component(s) impacted

sidenav-item

### Vivid Web Components version

latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

vivid

### CodeSandbox example

.

### Steps to reproduce the issue (if applicable)

hover or click on the sidenav-item with icon only

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
why does an icon-only needs to be full width?

**Comment by yinonov** [comment]
the expectation might be wrong here. perhaps the issue is nav with context being fluid rather than behave as inline and fit its content

**Comment by rinaok** [comment]
https://jira.vonage.com/browse/VIV-979
