### ISSUE TITLE
[Acronyms / initials]: new component - underlying

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#613]
The Avatar component has an option for Acronyms.
The Acronyms need to take the first 2 letters of a name and present them (uppercase?)
The font size need to be inheritable and so is the color.
Acronyms will not be exposed in the documentation same as `vwc-elevation`

**Comment by rachelbt** [comment]
**component name:**
I found no use case for _Acronyms_.
Most common by open-ui is _initials_

I suggest we call the component either `initials` or `avatar-initials`.

**component HTML rendered output**
<abbr>RB</abbr>

**component behavior**

An initial can be wither one letter or 2 letters.
- gets a name string - take the first letter of the first or first & second word. 
- any extra word will be ignored in the initial output.

**Comment by rachelbt** [comment]
**thoughts about accessibility and initials and code implementation:**
- there's no need for a separate component for avatar initials.
- the initials need to be wrapped with `<abbr>` that holds a title as well [w3c](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-dfn-element.html#defining-term)
- even-though there's a title - this is not enough for accessibility. aria-label is needed if the avatar is wrapped with `a` tag. the aria-label can be either on the initials or on the `a` itself. 
- screen-readers read the initials as 2 letters even if there was a title or aria-label. Should we add - aria-hidden if the letters are kind of "decorative"?

**things we need to consider:**
- are we implementing a basic initial creator or we are leaving it to the consumer?
-- if so - we need to have them set the title as well.
- should we add an aria-label recommendation in the docs in case it is wrapped with an `a` element for helping our consumers accessibility better?

**Comment by yinonov** [comment]
the w3c spec is a bit outdated (2011). can we trust it to be a standard?
as the implementation of context can vary, it is better to let consumers author it the way they think is best for their use-case.
we could maybe demonstrate a few examples or guide.
let's just start with trimming any string to 2 chars, extend to support piping multiple string to initials and leave a11y hardening to a later session

**Comment by rachelbt** [comment]
the title issue in MDN as well:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

The trimming - will we use the [literary](https://www.npmjs.com/package/initials) for that?

**Comment by yinonov** [comment]
> the title issue in MDN as well:
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
> 
> 
> 
> The trimming - will we use the [literary](https://www.npmjs.com/package/initials) for that?

It's not required. Can css trim what is displayed? That way accessibility tree will still contain the original context

**Comment by rachelbt** [comment]
> > the title issue in MDN as well:
> > https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
> > The trimming - will we use the [literary](https://www.npmjs.com/package/initials) for that?
> 
> It's not required. Can css trim what is displayed? That way accessibility tree will still contain the original context

we can't use css for trimming. CH unit is a certain width - and it doesn't fit itself to the characters:
![Uploading image.png…]()

**Comment by yinonov** [comment]
> > > the title issue in MDN as well:
> > > https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
> > > The trimming - will we use the [literary](https://www.npmjs.com/package/initials) for that?
> > 
> > 
> > It's not required. Can css trim what is displayed? That way accessibility tree will still contain the original context
> 
> we can't use css for trimming. CH unit is a certain width - and it doesn't fit itself to the characters: ![image](https://user-images.githubusercontent.com/7512792/192776714-f2e95545-b8d7-48b2-905d-b49da4f31164.png)

not something a wrapper with `overflow: hidden; width: 2ch` would contain?

**Comment by rachelbt** [comment]
> > > > the title issue in MDN as well:
> > > > https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
> > > > The trimming - will we use the [literary](https://www.npmjs.com/package/initials) for that?
> > > 
> > > 
> > > It's not required. Can css trim what is displayed? That way accessibility tree will still contain the original context
> > 
> > 
> > we can't use css for trimming. CH unit is a certain width - and it doesn't fit itself to the characters: ![image](https://user-images.githubusercontent.com/7512792/192776714-f2e95545-b8d7-48b2-905d-b49da4f31164.png)
> 
> not something a wrapper with `overflow: hidden; width: 2ch` would contain?

this is exactly what I did in this screen shot....
Anyway - this is not relevant anymore :)

**Comment by rachelbt** [comment]
done here: https://github.com/Vonage/vivid-3/pull/713
