### ISSUE TITLE
[list box]: migrate to fast

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#626]
### The problem

missing parity of list and items

### The solution

migrate and extend list and list items features

### Application/website

vivid

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

experience shows many different use-cases of listing and items; some are interactive, some are not

![image](https://user-images.githubusercontent.com/15140652/185881924-00ae90d1-2615-4d83-9b49-85111cb2f5b9.png)

- list item - interactive and non-interactive - the meta should nest within the list item
- list item - actions should not be nested within interactive list item due to its own actionable nature. if it’s non-interactive they should nest within it

these conditions, alone, mean that -
1. non-interactive list item affects the  list and its items roles to a simple `ul` & `li`?
2. meta & actions are 2 different slots? (meta might only be a property while actions need to be slotted)

note that actions of a list item shouldn't be nested within an interactive list item due to the [nested-interactive WCAG rule](https://dequeuniversity.com/rules/axe/4.4/nested-interactive?application=msftAI). they can, however, be placed as a next sibling to it, as listbox allows any content. question is this reflected in a UX sense...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
## Use cases

### VBC domains

- **contacts** - should be defined as an interactive _Tab_ controlling the document's right pane content.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/15140652/187206678-cc13310a-2c38-44da-9a48-7cfaa321c5d3.png">

Anatomy features -

- graphic slot (avatar)
- primary text
- secondary text
- secondary text meta aligned to the end (such behavior isn't featured in any of the vivid components)
- suffix slot (_meta_ / _actions_?)
  - caveat here is an action ("_more_" button) should not be nested within an action (tab). a workaround could be placing a suffix slot as a sibling to the element defined as tab. this could also backfire complying to the a11y tree standard as the container is defined as a _tablist_ and might not permit content other than a _tab_.

**Comment by rinaok** [comment]
@yinonov We don't have a `graphic` slot. Only a `meta` slot.
<img width="1194" alt="Screen Shot 2022-09-01 at 12 30 18" src="https://user-images.githubusercontent.com/10883919/187881550-7c08d818-dd59-40ea-9359-c2bf1374b710.png">

**Comment by rinaok** [comment]
Should we add a multiple choice option to the listbox component?
What should be the design for it? In Fast it looks like this:

<img width="109" alt="Screen Shot 2022-09-01 at 12 33 11" src="https://user-images.githubusercontent.com/10883919/187882197-aa389209-38bd-434e-9cb4-2e51b7c57e0e.png">

<img width="109" alt="Screen Shot 2022-09-01 at 12 33 00" src="https://user-images.githubusercontent.com/10883919/187882159-6ed8f346-4dd3-4e72-b563-0bffaa1d105c.png">

**Comment by rinaok** [comment]
When we click on an option inside the listbox, should we have a border?
In Fast, they have a different border for focus and for click:

regular:
<img width="116" alt="Screen Shot 2022-09-01 at 12 35 17" src="https://user-images.githubusercontent.com/10883919/187882628-f0ffe70e-17fc-40a7-acab-f2ef8b4c8597.png">

click:
<img width="118" alt="Screen Shot 2022-09-01 at 12 35 06" src="https://user-images.githubusercontent.com/10883919/187882589-5ac49d44-8824-4926-8aaf-ac5ecaad57de.png">

focus:
<img width="109" alt="Screen Shot 2022-09-01 at 12 35 29" src="https://user-images.githubusercontent.com/10883919/187882661-3a00dd17-cb74-4efa-b384-45bc7d5506e9.png">

**Comment by rinaok** [comment]
In vivid-2 we don't have a multiple choice in list. 

We have only `checkbox`:

<img width="248" alt="Screen Shot 2022-09-01 at 12 45 38" src="https://user-images.githubusercontent.com/10883919/187884871-6ec8761e-b6c1-42cc-82f9-303167
<img width="247" alt="Screen Shot 2022-09-01 at 12 46 43" src="https://user-images.githubusercontent.com/10883919/187885060-214b4f68-8fb0-4a12-ad89-1369960ffd47.png">
c64f7e.png">

And `radio` list:
<img width="249" alt="Screen Shot 2022-09-01 at 12 47 25" src="https://user-images.githubusercontent.com/10883919/187885207-ea3896f7-3c12-4ada-84f6-c3dddf79b2d0.png">
<img width="261" alt="Screen Shot 2022-09-01 at 12 47 34" src="https://user-images.githubusercontent.com/10883919/187885237-619d4237-f9ab-4261-b044-297ca034c064.png">

**Comment by rinaok** [comment]
Fast has menu component which can contain all the components we've mentioned above:


<img width="400" alt="Screen Shot 2022-09-01 at 12 52 20" src="https://user-images.githubusercontent.com/10883919/187886231-9c040fb6-16c4-4e24-ba93-d75fece029dd.png">

**Comment by yinonov** [comment]
notice the following [w3 listbox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)
> Avoiding very long option names facilitates understandability and perceivability for screen reader users. The entire name of an option is spoken as a single unit of speech when the option is read. When too much information is spoken as the result of a single key press, it is difficult to understand. Long names inhibit perception by increasing the impact of interrupted speech because users typically have to re-read the entire option. And, if the user does not understand what is spoken, reading the name by character, word, or phrase may be a difficult operation for many screen reader users in the context of a listbox widget.

this might weigh in on the choice whether should a meta property be applied (or more accurately not) to suffix the listbox item

**Comment by rinaok** [comment]
> notice the following [w3 listbox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)
> 
> > Avoiding very long option names facilitates understandability and perceivability for screen reader users. The entire name of an option is spoken as a single unit of speech when the option is read. When too much information is spoken as the result of a single key press, it is difficult to understand. Long names inhibit perception by increasing the impact of interrupted speech because users typically have to re-read the entire option. And, if the user does not understand what is spoken, reading the name by character, word, or phrase may be a difficult operation for many screen reader users in the context of a listbox widget.
> 
> this might weigh in on the choice whether should a **secondary text** & **meta** property be applied (or more accurately not) to suffix the listbox item

And also it says:
`
A listbox that allows a single option to be chosen is a single-select listbox; one that allows multiple options to be selected is a multi-select listbox.`

**Comment by rinaok** [comment]
@yinonov We already have a listbox, can we close this issue?
