### ISSUE TITLE
docs(avatar with icon badge that is not decorative)

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#637]
I’ve been researching the use case of an avatar with a big badge containing an icon, just like in the reference image I added.
My research have presented me with a few issues:

1.Most of published design systems don’t use this kind of element,
the only one that I found was Apple’s Human Interface Guidelines. Here’s the link:
https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/activity-views

2. It presents an accessibility issue:
Based on this article:
https://uxdesign.cc/make-your-design-system-accessible-part-2-icons-f3f7bd0b4b5a#:~:text=Interactive%20icons%2C%20also%20for%20desktop,by%20adding%20it%20via%20code.
this badge is not decorative, but functional, because it conveys information.

And based on this article:
https://w3c.github.io/wcag/understanding/target-size-minimum.html
the badge itself must have a size of at least 24X24px.

It is possible to create an invisible padding around the badge, but still, it is very problematic.
I put an Apple badge use case, badges I created, and the same badges with a background instead of transparent padding inside an Exploration Figma file
https://www.figma.com/file/BZFhGux6k3q462BSmTPYeX/Exploration?node-id=1900%3A237396
in order to demonstrate how much of the avatar’s territory it actually takes.

**Comment by yinonov** [comment]
@AyalaBu is this relevant?

**Comment by AyalaBu** [comment]
@yinonov I think that it can be closed.
We figured it out eventually.
