### ISSUE TITLE
[popup] create MVP

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#64]
follow
- https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md
- css wise: https://github.com/w3c/csswg-drafts/issues/5952?fbclid=IwAR04T94-OFZKnCFMXWoc0OJ11azMJ-1y9iR5qweCVCjezRa41MZXZ5HM_y8
- https://github.com/openui/open-ui/issues?q=is%3Aissue+is%3Aopen+popup

**Comment by rachelbt** [comment]
Summery of discussion:
we will use [popper.js](https://www.google.com/search?q=popper.js&rlz=1C5CHFA_enIL973IL973&oq=popper.js&aqs=chrome..69i57j0i512l4j69i60l3.448j0j7&sourceid=chrome&ie=UTF-8#:~:text=Popper%20%2D%20Tooltip%20%26%20Popover,popper.js.org) in <vwc-popup>

- Hide / show
--Using an OPEN attribute
-Roll - changeable roll?
-Dismissive:
--Close button option - dismissible
--Do we use light dismissed (by clicking anywhere else)? - need to be [researched](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md)
-Position
--Corner(relevant to the target) & Popupcornenr (relevant to itself using transform + translate)
--relevant to the trigger element can be implemented in one of the following:
---button that trigger the popup & both need to be wrapped with div in position: relative
---flixed 
-Style:
--Looks:
---Plain | With tail 
---Elevation - check with Joella
--Size:
---Inline-size
--Z-index issue - (should be handled as we did in side drawer or [other component](https://vonage.slack.com/archives/C013F0YKH99/p1627459542316200))

important links:
[select open close issues with fixed](https://github.com/material-components/material-web/issues/832#issuecomment-794372932)
[Discussion on: Who doesn't love some `<slot/>`s?
](https://dev.to/yinon/comment/1k8ch)

**Comment by rachelbt** [comment]
@jshenkman:
https://tmp.dev.vivid.vonage.com/1150/index.html?path=/story/alpha-components-popup--basic
please have a look at the popup in these aspects:
1. light theme
2. Alternate popup in light theme
3. the arrow of the popup is optional.
the content is whatever component it wraps. we added content to the story but it is only for presentation. 
The popup component is not the tooltip - its a step towards it :)
Once the popup is UI OK we will remove it from StoryBook for it is for internal use (wrap tooltip, replace the menu surface, etc)

**Comment by jshenkman** [comment]
Everything looks great!!!! @rachelbt @rinaok nice job!!
