### ISSUE TITLE
[Layout] define basis for columns width

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#643]
rem was indeterministic as I presumed the baseline (root) is 16px which isn't in every case. change the baseline now broke the UI tests. this would need a revisit to determine the best bases for each

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/pull/617#discussion_r960593811_

**Comment by rinaok** [comment]
@rachelbt should we close this? or open a ticket in Jira?

**Comment by rachelbt** [comment]
I really don't know what was @yinonov intentions to do with that. maybe use the size as we are using in in buttons?

**Comment by rinaok** [comment]
@rachelbt I don't know, so I'm closing this :)

**Comment by yinonov** [comment]
yeah that isn't very clear now, is it? it was originally posted by me in https://github.com/Vonage/vivid-3/pull/617#discussion_r960593811
