### ISSUE TITLE
[typography styles]: scope styles in app region

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#647]
### The problem

Apps migrating to vivid styles may experience conflicts with other libraries affecting styles in their app.

for example, applications dependent on Volta for typography would have different styles and fonts applying styles on the same 1st level tags selectors as Vivid does. Thus result in wrong style.

### The solution

utilize [css cascade layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) to allow scoping of styles within specific regions of an app.

provide and document a codepen in our docs (styles) to help quickly onboard authors migrating from legacy libraries.

### Application/website

null

### Business priority

Medium Priority = upcoming release but is not pressing

### What time frame would this ideally be needed by (if applicable)

sprint 22

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
I started checking this issue but I’m not sure about the case of vivid use inside applications.
For sites that already using Vivid and Volta or whatever, putting vivid style imports inside `@layer` will not help, or even can make thing worse, as un-layered styles have the highest priority.
If possible, inserting Volta css inside `@layer` can help “un-layered vivid” imports to override Volta.
attaching a codepen with vivd-next as un-layered style and “Volta” style inside `@layer`:
https://codepen.io/rachelbt/pen/ExLapRx

**Comment by yinonov** [comment]
we don't want any to precede  the other. authors may want to choose a part of the page to be vivid and then gradually expand the scope of migration (in steps) to ancestor element and later high up the tree until they reach top of their document to complete a migration process.

**Comment by rachelbt** [comment]
Adding the Vivid style as layer doesn't help to encapsulate the styles.
If there's an un-layered style they have higher specificity.
attaching a code-pen to summaries it:
https://codepen.io/rachelbt/pen/WNJQXYd
