### ISSUE TITLE
[vertical tabs]: component research

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#659]
There is a request by design teams to create a list item with custom content.
Some of the use cases seem problematic from UX and accessibility points of view.

In order to reach the correct decision there are a few components that need to be researched:
1. Vertical tabs
2. List item
3. List box

Right now the component in the progress of research is vertical tabs.

![Image](https://user-images.githubusercontent.com/106529909/188488145-b1466f2b-9a03-45b3-8d25-7d7762064cdb.png)

**Comment by AyalaBu** [comment]
Vertical Tabs research is here:

https://www.figma.com/file/QG5hvuw5qsfS0XYMVJ6V3L/Vivid-UI-Kit---Exploration?node-id=3945%3A78517

**Comment by AyalaBu** [comment]
As I continued my research (finished writing also the list item research in the same link 👆),
I began going over the variants of the components that exist in the UI Kit).

I went over the list item only in the meantime, this is the branch:
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/branch/HGrZrrVhSiRhkwbVRONmA9/Vivid-UI-Kit---2.0?node-id=1968%3A567

I put a red background in the "List - item" section under the variants that are not list items at all by definition (based on my research), and need to go. I put the yellow background under the variants that I am not sure about. They actually didn't appear in any other design system that I looked in, but I wonder maybe we will still have use for them.

@yinonov what do you think?

**Comment by yinonov** [comment]
as discussed, we need to focus on each individual component and role. start by defining tabs (horizontal / vertical), menu items, options.

what we're calling _"list-item"_ is actually an abstract pattern of what the mentioned components extract anatomy from.
each component might extract a different subset as some components like option should have more than a single line text and a decorative icon
we need to give that _"list-item"_ a more suitable name for a pattern as list-item is a reserved role within the web context.

**Comment by AyalaBu** [comment]
I think that I will divide this into categories, and treat each of them as a separate component. 
It kind of is now, but still needs some attention.

**Comment by AyalaBu** [comment]
@yinonov 
After doing some research I found that 

**The variants that exist in vertical tabs are:**
1. Tab with primary text only
2. Tab with primary text + icon
3. Tab with primary text + text badge
4. Tab with primary text + notification - indicator only
5. Tab with primary text + number of notifications - number badge
6. Tab with primary text + Alert notification (high, moderate & low severity)

Also were variants that included more that two content components, which are:
1. Tab with primary text + icon + text badge
2. Tab with primary text + icon + number of notifications - number badge
3. Tab with primary text + icon + Alert notification (high, moderate & low severity)

(!) Not even once I saw a vertical tab that included:
1. Primary + secondary text
2. Checkbox
3. Radio button
4. More actions icons
I believe that this is something we should take into consideration

**The variants that exist in list item (option) are:**
1. Primary text
2. Bullet (ul) + primary text
3. Number (ol) + primary text
4. Primary + secondary text (Vertical & Horizontal view)
5. Primary text + choice icon (V)
6. Primary text + radio button
7. Primary text + checkbox
8. Primary text + image (information icon)

**The variants that exist in menu item (option) are:**
1. Primary text (horizontal + vertical)
2. Primary text + submenu action (dropdown arrow)
3. Primary text + badge
4. Primary text + subheaders (secondary text)
5. Primary text + icon
6. Primary text  + icon + choice icon (V)
7. Primary text + status notification icon (high, moderate & low severity)
8. Primary + Secondary text

In our UI Kit 2.0 there are list item variants that I think are not needed based on my research:
1. List item with primary text, radio button/checkbox + action (dropdown arrow/more actions icon)
2. List item with primary & secondary text, radio button/checkbox + action (dropdown arrow/more actions icon)

Most of the variants do need some attention and rearranging,  but also as I written in the issue 703:
https://github.com/Vonage/vivid-3/issues/703

I believe there is need to create a new slotted list component

**Comment by yinonov** [comment]
can we have a visual representation along side this?

**Comment by AyalaBu** [comment]
The research is in this link:

https://www.figma.com/file/QG5hvuw5qsfS0XYMVJ6V3L/Vivid-UI-Kit---Exploration?node-id=3945%3A78518

**Comment by AyalaBu** [comment]
The new component is called tile,
and its variant are here in this link (in the meantime):

https://www.figma.com/file/QG5hvuw5qsfS0XYMVJ6V3L/Vivid-UI-Kit---Exploration?node-id=4129%3A55647

**Comment by AyalaBu** [comment]
@yinonov 
In the meantime the only additional request to the new components was to create an "option-item" with two lines, that also in some situations can feature a "check" icon like in this use case:

![image](https://user-images.githubusercontent.com/106529909/202897637-80823732-cd1a-43fb-9241-1493bc969c73.png)

Screen reader read it this way:
1. First line of text
2. Second line of text
3. checkmark (was pronounced as "checked")

Also a component like that appears in multiple design systems,
these are a few examples:

https://m2.material.io/components/lists#interactive-demo

https://ant.design/components/list

https://getbootstrap.com/docs/4.3/components/list-group/#custom-content

https://developer.microsoft.com/en-us/fluentui#/controls/web/list

Based on this information I don't see a problem to provide this option item variant.
