### ISSUE TITLE
[listbox option] have no selected indicator

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#681]
@ayalaBu

listbox options, when are selected / checked, are styled by background color only. does it comply with rules? should we add another indicator?

<img width="171" alt="image" src="https://user-images.githubusercontent.com/15140652/190326084-42060531-8f36-4eac-ae51-b168da43d925.png">

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/issues/635#issuecomment-1247618771_

**Comment by AyalaBu** [comment]
@yinonov 
selected/checked and other states also don't have a special accessibility rules,
but it can be not a very good ui if there is no indication.
So maybe there can be an indicator like in the picture you placed,
but maybe switching a font weight to bold can also be an option.

**Comment by yinonov** [comment]
I doubt that it has no WCAG rules, or at least not being addressed in next WCAG iterations. assigned this task to you
