### ISSUE TITLE
[popup]: extend light dismiss capabilities

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#687]
### The problem

https://github.com/Vonage/vivid-3/blob/b4c9b0af36f787cfc47f13de6a3f144921c5a6be/libs/components/src/lib/popup/README.md?plain=1#L72-L74

Light dismiss implementation in popup isn't sufficient according to the open-ui spec and other explainers -
There's more to it than click outside

behavior should support closing when click outside, click on close button, click on anchor, click on escape, resize, scroll etc'.

question: should we add indication on how popup was closed in the fired closing event? such detail on closing exist in a dialog pattern.

see also
> @yinonov When the anchor is in focus, pressing ESC closes the popup. I am not sure it is part of the light dismiss. I made a research, don't remember all of it, but tooltip should close on ESC. Here for example: https://www.lightningdesignsystem.com/accessibility/patterns/tooltip/

_Originally posted by @rinaok in https://github.com/Vonage/vivid-3/pull/676#discussion_r970682471_

https://open-ui.org/components/popup.research (Search page for light dismiss)

https://developer.chrome.com/blog/pop-ups-theyre-making-a-resurgence/

### The solution

as native popup seem to gain support and attention, we should adopt a polyfill and set our course towards using the specified interface instead of patching in all its requirements ourselves.

https://github.com/oddbird/popup-polyfill

### Business priority

Medium Priority = upcoming release but is not pressing

**Comment by yinonov** [comment]
needs triage

**Comment by rinaok** [comment]
Steps to add popup-polyfill:

- Install it with `npm install @oddbird/popup-polyfill`
- Add popup attribute to our popup component (It should be named `data-popup` because this feature is still experimental).
- The popup attribute can take the following values: `auto`, `hint`, `manual`.
- Implement all [popup APIs ](https://developer.chrome.com/docs/web-platform/popup-api/) and document it.

**Comment by rinaok** [comment]
https://docs.google.com/document/d/1NTiftSlmfq1ntwPK_9mPECiGg6Eo98l37PiiAwoT5j8/edit#heading=h.x623h7v63x38
