### ISSUE TITLE
[Indicator additional size]: adding another size (20px) or creating a few new icons

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#702]
Had another meeting with Yamit and it included a conversation with her another use case.
When the user chooses his/her availability status it causes a dropdown to open with the existing options.
Right now it looks like this:

![Image](https://user-images.githubusercontent.com/106529909/192777388-7823542b-b371-4b8c-85f2-fb4bab3b1418.png)

Alas, it presents us with a problem:
The options presented are actually the avatar indicators that are existing right now.
This situation makes me wonder should we:

1. Use in this use case the indicator that exists now in its larger size, and in this case the options will look like this:

![Image](https://user-images.githubusercontent.com/106529909/192777813-8b329252-0a22-4239-9b59-14f11ebb6a8d.png)

Yamit said that she doesn't actually have a problem with the way it looks right now,
but I'm bothered by the different sizes of indicators/icons

**OR**

2. Create another indicator size (20px) that will be used only in this case, also in this case there's no need for "audio/video call" option

**OR**

3. Create additional icons that look like the indicator statuses that we have already (available, do not disturb, busy, away & offline).

**Comment by AyalaBu** [comment]
@yinonov 
What do you think about how it should be handled?
I am actually inclined to leave it as it is, but I wonder maybe we should consider adding another size only for the sake of size consistency in the side drawer element?

**Comment by yinonov** [comment]
Avatar presence cannot be used outside its own Avatar scope. it's an avatar related interface.
This implementation should be manually authored by consumers by using a condensed badge (which should extend support for icon-only).

alternatively, indicator icon representation can be omitted to simply text as in
<img width="297" alt="image" src="https://user-images.githubusercontent.com/15140652/192963921-24af4ae2-d68d-4810-b6a7-e3af504d474c.png">

but that's a UX decision.

**Comment by AyalaBu** [comment]
I believe that maybe it can be omitted to just text, 
but I got the impression that this is not what she wants.
She wants to have the icon aside text to match the indicator.
So maybe we should consider creating a few new icons that look the same?

**Comment by yinonov** [comment]
can you please share the link to Figma design here?

**Comment by AyalaBu** [comment]
Voila!

https://www.figma.com/file/FomC4lmRFnAbFbq9vtMi18/VBC-Availability-Status?node-id=205%3A49257

**Comment by AyalaBu** [comment]
I tried using the badge without text, but what we have right now creates an elliptic shape.

![Image](https://user-images.githubusercontent.com/106529909/193000663-c7698e44-39ca-44ed-ae9f-aab63d4ccf8b.png)

**Comment by yinonov** [comment]
> (which should extend support for icon-only)

👆

**Comment by AyalaBu** [comment]
@yinonov  
I created a series of badges that contain icon only.
They are in this branch:

https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/branch/eiSBjHTMsNrioTbA1Kohru/Vivid-UI-Kit---2.0?node-id=1916%3A23428

Need reviewing and (hopefully) merging

**Comment by yinonov** [comment]
commented in figma

**Comment by AyalaBu** [comment]
Finished fixing what you wrote in the comment
Do you mind going over it?

**Comment by AyalaBu** [comment]
The component was created and successfully merged to Vivid UI Kit 2.0:

https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=18139%3A74251

In the meantime light mode only
