### ISSUE TITLE
[Note appearance]: research

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#729]
After checking appearances existing in our design system, these are the appearances that I found:
1. regular background (500)
2. soft background (100)
3. alternate background (neutral 950)
4. outline 1px (500)

New note is the only component that combines two appearances: soft background + outline 1px.
A decision must be reached:
Should we assign to the note component one of the existing appearances that are used in plenty cases in the design system, or do we create an additional appearance that in the meantime exists in the note component only

**Comment by rachelbt** [comment]
the soft / subtle is used un badge as well. 
There's an option for changing the soft **colors** with understanding that  the change will effect badge or if there are other places that it is used.

**Comment by AyalaBu** [comment]
The note appearance is open for opinions and voting right here:

https://www.figma.com/file/BZFhGux6k3q462BSmTPYeX/Exploration?node-id=2183%3A256622

**Comment by AyalaBu** [comment]
The voting between the designers showed that they prefer the original design created by Joella (soft BG + border).
So there is need to create another appearance model that suits this situation.

**Comment by yinonov** [comment]
fieldset with connotation could be an option

**Comment by yinonov** [comment]
review #634

**Comment by AyalaBu** [comment]
@yinonov 
Looks great!
