### ISSUE TITLE
[AA to AAA accessibility standard]: research

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#736]
In order to apply accessibility standarts to our products it needs to be checked and researched.

**Comment by AyalaBu** [comment]
In the meantime these are the components that were checked,
and these are the token changes that need to be applied for it to be AAA:

**Actions:**


![Image](https://user-images.githubusercontent.com/106529909/194739340-7551f689-68e5-4dc0-a8f1-c65213b778ed.png)


**Form controls:**


![Image](https://user-images.githubusercontent.com/106529909/194739348-2d41e08f-16fe-4686-82d9-0b583bba9ea1.png)


**Status:**


![Image](https://user-images.githubusercontent.com/106529909/194739352-c16ba4a2-95cb-4055-8df7-2d94fa7a585b.png)


**Display:**


![Image](https://user-images.githubusercontent.com/106529909/194739360-824865fa-3fe5-490f-aa52-aa4c67bf0a5d.png)

**Comment by yinonov** [comment]
could this be presented live to the team? I fear some of the terminology used here may conflict and can be misleading
