### ISSUE TITLE
[Component to do list]: creating new component convention

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#739]
A checklist of how we create a new component must be created.
It should include its documentation page, design principals, caveats, a11y, anatomy etc’…

**Comment by yinonov** [comment]
current process of creating component in figma is arbitrary and design course is set by individual scattered requests.
each component design should follow the same structure, sections, anatomy and anything else we define in this scope.
ideally, this should first follow a best practice defined by the community.

following next, published component would expose to designers the closest interface possible to match development
