### ISSUE TITLE
[number field] controls steal focus

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#746]
A focused number field has a focus ring indicating its state.

![image](https://user-images.githubusercontent.com/15140652/195629046-d37768af-347c-43b8-9c14-9763c0ce471d.jpeg)

When interacting with its controls, the focus ring is no longer shown

![image](https://user-images.githubusercontent.com/15140652/195629068-ca860241-4bed-45d2-b44f-51f5c3a1753c.jpeg)

Focus ring should still be visible as it is expected that focus remains on the control

This occurs on iOS chrome

**Comment by YonatanKra** [comment]
@yinonov 
This seems to be resolved. Am I correct?
Reopen if still exists.
