### ISSUE TITLE
[Warning connotation token change]: changing the token in warning elements

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#755]
Components that have filled appearance like buttons, badges, banners etc. have a color token 500 in all the connotations.

This presents a problem with the warning connotation, since the yellow turns to orange mustard color.
It is a known practice to treat the warning connotation differently, as explained in this article:

https://uxdesign.cc/the-dark-yellow-problem-in-design-system-color-palettes-a0db1eedc99d

In the Vivid 3 documentation the warning component receives the same token number as any other connotation,
while in the original design (Vivi UI Kit 2.0 Figma file) it is 300, and was originally designed this way.

There came a request to change the 300 to 200, but since in the documentation it has a 500 token, this case needs special treatment.

**Comment by AyalaBu** [comment]
The issue was discussed with Yinon
The solution that was proposed:
1. Creating yellow scale that consists of light shadows of yellow
2. The dark text (if needed) will use a separate (it can be orange in this case) scale

**Comment by yinonov** [comment]
why do we have an orange scale? do we use it anywhere? is it part of the brand? red can be sufficient as well

**Comment by AyalaBu** [comment]
@yinonov 
I saw orange used in the calendar, although I really don't know if we actually need it.

Also, adding my yellow (warning) components research and proposal:


![Image](https://user-images.githubusercontent.com/106529909/200162822-95d1f79d-1ca2-428b-82ad-d3fb29f947f4.png)
![Image](https://user-images.githubusercontent.com/106529909/200162821-1118b910-afbb-4190-a04e-4f602f83ed55.png)
![Image](https://user-images.githubusercontent.com/106529909/200162820-018d3af2-691b-4437-8e88-44097cf84302.png)

@yinonov 
So what do you think?

**Comment by AyalaBu** [comment]
@yinonov 

After some research and thinking another scale was created 
It will look like this:


![Image](https://user-images.githubusercontent.com/106529909/202390462-1b56313c-a024-4db3-8699-311d436350aa.png)

tokens colors:

| Color number | Hex Code |
| -------------- | ------------- |
| 50 | #FEF0BC  |
| 100  | #FBD978  |
| 200  | #FACC4B  |
| 300  | #FBC333  |
| 400  | #FBB733  |
| 500  | #F59402  |
| 600  | #DE6807  |
| 700  | #933F06  |
| 800  | #522801  |
| 900  | #2A1502  |
| 950  | No change  |

**Comment by AyalaBu** [comment]
@yinonov 
Since the precious solution didn't actually manage to solve our problem,
this is what I propose:

1. Change the Warning **500** color token to **300** (appears in _background_ and _outline_)
2. Change the text color token to **--vvd-color-primary**

The solution is not perfect, but at least it's a bit nicer looking.

So what do you think?

**Comment by yinonov** [comment]
that's the outcome in dark mode
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/15140652/203019165-8147bcee-0f68-48d1-b3ae-6d219f4c7266.png">
