### ISSUE TITLE
[badge]: omit sizes

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#756]
As part of moving from density to size, removing the option of 3 different sizes in badge.

**Comment by rachelbt** [comment]
@AyalaBu 
Do you know if dense or condense are used in badges?

**Comment by AyalaBu** [comment]
@rachelbt 
In badges we actually have three sizes: dense, default & large (20px, 24px & 28px)

**Comment by rachelbt** [comment]
> @rachelbt In badges we actually have three sizes: dense, default & large (20px, 24px & 28px)

 I know.
 I wanted to know if you know if its in use (the dense + enlarged).
We want to remove them.

**Comment by AyalaBu** [comment]
We can put a question in slack
But I know for sure that the dense size with icon only will be used in some project Yamit is working on.
It was created for this specifically.

**Comment by rachelbt** [comment]
@AyalaBu 
I removed the sizes and set the height of the badge to 20px as [almost all the designers said ](https://vonage.slack.com/archives/G0169E0RF6K/p1666527121400709) they are using the condense.

have a look if it looks OK. the icon looks a bit small. Its the same as it is now - but now there's no "normal" with 24px heigh:
https://vivid-p8ssvjtftbhg.deno.dev/components/badge

**Comment by AyalaBu** [comment]
@rachelbt 
Looks great!
