### ISSUE TITLE
[docs] document css public references

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#770]
some of the Vivid design identities are referred to by template styles.
to customize components style in a systematic level (rather than per-mutating individual components) tokens are provided in run-time (e.g. typography base, size-density etc'.)

document and provide usage examples in docs

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/issues/768#issuecomment-1296700785_

**Comment by yinonov** [comment]
featured options

```css
--vvd-font-family-upright: arial; // customize the default font
--vvd-font-family-monospace: monospace; // customize the code font
--vvd-size-font-scale-base: 1rem; // customize the typography scale's base font size
--vvd-size-density: -1; global density integer is used to scale all components sizes. allowed values are 0, 1, -1 (0 being default)
```

**Comment by yinonov** [comment]
In addition to documenting density, the site or code blocks demos can feature a control to choose density value

**Comment by yinonov** [comment]
should add typography scale to the scope of this issue

![image](https://user-images.githubusercontent.com/15140652/199458874-b3982a0a-dc5b-4553-865d-f23bb0b7f50c.png)

**Comment by yinonov** [comment]
regarding `--vvd-size-font-scale-base: 1rem;` -
Vivid default base is 16px.
the idea behind setting the base to `1rem` is to align back with browser's default font size where all other typefaces descend from. this is an accessibility issue where if a user enlarge their browser's font size, the component should follow
![image](https://user-images.githubusercontent.com/15140652/199531177-05738ba7-34e3-4c73-91f3-ae57116d1b81.png)

**Comment by olaf-k** [comment]
> In addition to documenting density, the site or code blocks demos can feature a control to choose density value

I'll address that in a separate PR.
