### ISSUE TITLE
[components] include checked member in option component

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#771]
@yinonov I think it's better not to include it in the docs right now, and only add it when the listbox will be ready./
Then we could add an example with a listbox and write this comment:

`The checked state is used when the parent listbox is in multiple selection mode. To avoid accessibility conflicts, the checked state should not be present in single selection mode.`

_Originally posted by @rinaok in https://github.com/Vonage/vivid-3/pull/760#discussion_r1009311880_

**Comment by rinaok** [comment]
@yinonov 

The user should not toggle by himself the `checked` attribute. 
Therefore, I think that we should not add it to our docs.

If we add the checked attribute to the option by ourselves, we will not see any visible change.
Add the following code example [here](https://explore.fast.design/components/fast-listbox):

```
<fast-listbox multiple>
    <fast-option value="1" checked>Option 1</fast-option>
    <fast-option value="2">Option 2</fast-option>
    <fast-option value="3">Option 3</fast-option>
</fast-listbox>

```

**Comment by yinonov** [comment]
that's true
