### ISSUE TITLE
[calendar]: DST issue in tests

### ISSUE THREAD

**Issue by olaf-k** [Vonage/vivid-3#774]
### Description

The calendar test `should show recent sunday as first day of this week` fails.
![image](https://user-images.githubusercontent.com/1153034/199073479-245b6331-d5a7-4df5-aecd-11b0f3a69690.png)

The test compares the calendar display (which is fine) to the date of the "previous Monday", but the functions that generate the expected date are DST-sensitive because they compare date + time (midnight based).

### Component(s) impacted

Calendar only.

### Vivid Web Components version

v3

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

Not a big deal since the widget itself behaves fine.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by YonatanKra** [comment]
@olaf-k 
Is this still happening to you?
Only on your laptop because of time diffs?

**Comment by olaf-k** [comment]
> @olaf-k Is this still happening to you? Only on your laptop because of time diffs?

it doesn't happen anymore as we're past the DST change weekend but it will reoccur yes.
it's not due to time difference between us, it's due to the fact that the helpers in the test compute midnight-based dates which are susceptible to DST. I'll have a look when I have an hour to myself, it's not a big deal.
