### ISSUE TITLE
size density issues in changing to 1 or -1

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#780]
- [ ] number-field composition
- [x] text-field composition
- [x] buttons (icon inside needs to be half of button-size)
- [x] banner (~~icons~~ buttons inside it)
- [x] checkbox
- [x] radio-button
- [x] dialog icon
- [x] fab
- [ ] all _tile_ nested elements

a point to think of:
Should typography be aligned with base-size-density and change accordingly?

**Comment by yinonov** [comment]
proceeds #773

**Comment by yinonov** [comment]
resolved banner min-block-size. what issues did we face with its icons?

**Comment by rachelbt** [comment]
> resolved banner min-block-size. what issues did we face with its icons?

the icon is a mistake. I'll edit it. if the typography stays the same than the icon should too.
The buttons in the banner should align to the size-density change.

**Comment by yinonov** [comment]
dialog icon resolved to size describe in [VIV-825](https://jira.vonage.com/browse/VIV-825)

**Comment by yinonov** [comment]
typography now scales with size density https://vivid-pmbsb3qa46j0.deno.dev/components/text-field

**Comment by rachelbt** [comment]
> typography now scales with size density https://vivid-pmbsb3qa46j0.deno.dev/components/text-field

I'm not sure we want that - or if so - not sure the base font size should scale under 14px

**Comment by yinonov** [comment]
> > typography now scales with size density https://vivid-pmbsb3qa46j0.deno.dev/components/text-field
> 
> I'm not sure we want that - or if so - not sure the base font size should scale under 14px

it wont 🙂

**Comment by rachelbt** [comment]
> > > typography now scales with size density https://vivid-pmbsb3qa46j0.deno.dev/components/text-field
> > 
> > 
> > I'm not sure we want that - or if so - not sure the base font size should scale under 14px
> 
> it wont 🙂

but it does...
![image](https://user-images.githubusercontent.com/7512792/200173224-7a0d5d0e-7bb8-4278-a01f-aaf45389ab1f.png)
