### ISSUE TITLE
[docs] navigating should not reload the entire page

### ISSUE THREAD

**Issue by olaf-k** [Vonage/vivid-3#788]
### The problem

Navigating the doc entries require page reloading, which:
1. is unnecessary perf-wise,
2. loses the nav scroll position.

### The solution

Don't know yet 😶 1 is not a big deal but I find 2 annoying.

### Application/website

https://vivid.deno.dev/

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
Our docs aren't a SPA. What measures do jamstack apply? There are some heavy players in the market. Suggesting to review Astro, 11ty community

**Comment by olaf-k** [comment]
> **Our docs aren't a SPA**. What measures do jamstack apply? There are some heavy players in the market. Suggesting to review Astro, 11ty community

I think the first assertion is debatable, but if the spirit is "it doesn't need an entire framework just for that" I agree. I'll think about ways to solve 2 and will have a look at your suggestions.
