### ISSUE TITLE
[Calendar] style columns by query

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#79]
Use container queries to style columns as in
https://css-tricks.com/next-gen-css-container/#container-queries-media-queries

**Comment by rachelbt** [comment]
I wish we could use that but CSS container queries are still [not supported](https://caniuse.com/css-container-queries)....
The examples in the article are experimental and can be seen only in Chrome Canary with the experimental #enable-container-queries flag turned on.

**Comment by yinonov** [comment]
it has little cost and align to progressive enhancement. low priority...

**Comment by yinonov** [comment]
@rachelbt lets use container queries. Today!

https://github.com/GoogleChromeLabs/container-query-polyfill

**Comment by rachelbt** [comment]
@yinonov is this issue still relevant?
