### ISSUE TITLE
default font 

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#795]
finding a default font to replace Spezia

**Comment by rachelbt** [comment]
Problems:
We are using font-stretch to select condense, expand and more in the Spezia font but it does not apply to all fonts:

> You can use font-stretch to select a condensed or expanded face from such fonts. If the font you are using does not offer condensed or expanded faces, this property has no effect.

https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch

**Comment by rachelbt** [comment]
@AyalaBu @yinonov 
can you please have a look:
this one is Mulish:
https://vivid-f1qvg1ajwtdg.deno.dev/

this one is Monserat:
https://vivid-30s4sjk9dsg0.deno.dev/

WDYT?
@AyalaBu do you have a better suggestion?

**Comment by AyalaBu** [comment]
@rachelbt 
I think that I like the Monserrat more, although both are great

**Comment by yinonov** [comment]
Can we create a gist or a repo to guide vonage how to use Spezia font?

**Comment by rachelbt** [comment]
DONE and implemented :)
