### ISSUE TITLE
[Calendar] add containment

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#80]
> The contain CSS property allows an author to indicate that an element and its contents are, as much as possible, independent of the rest of the document tree. This allows the browser to recalculate layout, style, paint, size, or any combination of them for a limited area of the DOM and not the entire page, leading to obvious performance benefits.
>
> This property is useful on pages that contain a lot of widgets that are all independent, as it can be used to prevent each widget's internals from having side effects outside of the widget's bounding-box.

Calendar meets the above criterion. adding relevant style may improve its performance in a page

https://developer.mozilla.org/en-US/docs/Web/CSS/contain

**Comment by rachelbt** [comment]
adding the contain property (with content or paint) changes the element stacking stacking context, so there might be issues regarding z-index, that is set to 0 as from this issue:

- https://vonage.slack.com/archives/C013F0YKH99/p1627459542316200
- https://github.com/Vonage/vivid/pull/995/files
[further reading about contain and stacking](https://css-tricks.com/almanac/properties/c/contain/)

**Comment by yinonov** [comment]
it's ok for it to have a z-index of 1. it has no overlapping intent

**Comment by yinonov** [comment]
can still investigate
