### ISSUE TITLE
[text area] disabled state isn't delegating

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#804]
text area, when set to disabled doesn't delegate, so the disabled state isn't applied to the shadowed native text area.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/15140652/200496818-6765667f-9690-4f8a-897f-ff6eb98339f0.png">

**Comment by YonatanKra** [comment]
@yinonov 
Seems to be resolved with the tokens rehaul.
