### ISSUE TITLE
[disabled]: not-allowed cursor in text-filed, area and numberfield

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#811]
https://github.com/Vonage/vivid-3/pull/802#issuecomment-1308505963

**Comment by yinonov** [comment]
> Not related to your changes but in scope of appearance consistency:
> 
> * number/text fields & text-area lack the `not-allowed` cursor in disabled state
> * the readonly state for checkbox/radio/switch should probably not keep the `pointer` cursor

me and @olaf-k discussed opening an issue as the question whether [read-only should exist in checkbox arise](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly)
> The attribute is not supported or relevant to <select> or input types that are already not mutable, such as [checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) and [radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) or cannot, by definition, start with a value, such as the [file](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) input type. [range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) and [color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color), as both have default values. It is also not supported on [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden) as it can not be expected that a user to fill out a form that is hidden. Nor is it supported on any of the button types, including image.

**Comment by rinaok** [comment]
https://jira.vonage.com/browse/VIV-999
