### ISSUE TITLE
[switch]: style adjustments 

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#812]
after [this is merged ](https://github.com/Vonage/vivid-3/pull/802#pullrequestreview-1174195254)- some adjustments need to be set to bring the style to what it was before :)

**Comment by yinonov** [comment]
was very simple to solve and still related to #802 
see - [support switch hover state](https://github.com/Vonage/vivid-3/commit/42b4057859990001d4d4e8e7dabf3164c5b5c9e2)
