### ISSUE TITLE
[Alert/Success field]: icon change

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#814]
@YonatanKra 

 Alert/Success fields -

in the remark part the icon must be changed
**Alert** > error icon must be changed to _line_
**Check** > check-circle icon must be changed to _line_

**Comment by rachelbt** [comment]
@AyalaBu 
the icons that we have are what was in the Figma file and in Vivid-2:
![image](https://user-images.githubusercontent.com/7512792/201513174-9bc952c9-dd2b-4a33-98a8-b84336a50493.png)


you want to change them to this?
![image](https://user-images.githubusercontent.com/7512792/201513095-ad74166c-6b0c-462a-b99a-c108a3e28c27.png)

![image](https://user-images.githubusercontent.com/7512792/201513102-c12e000f-5c3a-4b0c-a567-3847addafa37.png)

**Comment by rachelbt** [comment]
@AyalaBu please verify that its OK:
https://vivid-1zghxwmg5mvg.deno.dev/components/text-field

**Comment by AyalaBu** [comment]
@rachelbt 
Splendid !
