### ISSUE TITLE
[Text-Area]: Missing attributes

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#828]
### Description

The text-area component is missing the following attributes:

Maximum length
Minimum length
Required
Resize
Columns

and some more.

Also I found some bugs, for example:

The disable is not really disabled, you can click on it. The readonly also doesn’t act like it should.

### Component(s) impacted

text-area

### Browser

Chrome

### Vivid Web Components version

latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

.

### CodeSandbox example

.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by YonatanKra** [comment]
Regarding validation - there's a known issue in we follow in Fast in #752.

**Comment by YonatanKra** [comment]
Regarding the missing attributes - how do you see they are missing?

**Comment by rinaok** [comment]
> Regarding the missing attributes - how do you see they are missing?

@YonatanKra They are missing in the docs.
