### ISSUE TITLE
[toggletip]: create a new component

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#838]
### The problem

we’re often asked for vivid tooltip to support interactive content (e.g. links).
The reason tooltip hinders any content other than plain text is to improve a11y concerns which are often overlooked in development, and tooltip in that sense require a little chat every time it's raised.
a tooltip - toggletip comparison [nice summary](https://web.dev/building-a-tooltip-component/#toggletip-vs-tooltip) 

### The solution

create a dedicated component for toggletip and reduce the wrong use of tooltip

### Application/website

null

### Business priority

Medium Priority = upcoming release but is not pressing

### Examples

https://vonage.slack.com/archives/C013F0YKH99/p1667547664898289

following thread have some helpful information
https://web-a11y.slack.com/archives/C042TSFGN/p1668458681197569

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rinaok** [comment]
https://jira.vonage.com/browse/VIV-865
