### ISSUE TITLE
[Field with new UX behavior]: research

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#840]
There came a request to create a field with information icon that is able to show some additional information: 

![Image](https://user-images.githubusercontent.com/106529909/202203575-90c6f343-650f-417a-a538-4c567375771c.png)

Right now the questions are:
1. Was ever used in previous designs? Did it ever exist at all?
2. How should be described in words?
3. What is the correct way to present?
4. What are the design principles?
5. Does it make a helper text redundant?
6. Could be called toggle tip?

The issue needs to be researched

**Comment by yinonov** [comment]
it's a [Volta legacy outdated design](https://legacy.vivid.vonage.com/?path=/story/forms-inputs--composite-prepend)

the modern Vivid implementation groups elements & controls with [action-group](https://vivid.deno.dev/components/action-group#tight)
