### ISSUE TITLE
[Split-button] new component

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid-3#85]
A split button is a dual-function menu button that offers a default action as well as the possibility of choosing a different action by selecting from a set of alternatives.

A split button is a button with two components: a label and an arrow (chevron); clicking on the label selects a default action, and clicking on the arrow opens up a list of other possible actions.

Two types of 'split-button' - 
1. Default action Split button - the default action always stays the same
2. Persistent Split Buttons - the default action changes to the last action selected by the user (from the list of actions in the split-button menu).

Great reference - [Article by NNG](https://www.nngroup.com/articles/split-buttons/)

**Comment by yinonov** [comment]
see open-ui/open-ui#408

**Comment by jshenkman** [comment]
Some examples from other systems - 
1. [Spectrum](https://opensource.adobe.com/spectrum-web-components/components/split-button/) 
2. [Fluent](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) 
3. [MUI](https://mui.com/components/button-group/#split-button)
4.

**Comment by jshenkman** [comment]
Request from Aviad in Meetings to support split-button to stacked buttons as well

**Comment by yinonov** [comment]
shouldn't close yet
