### ISSUE TITLE
[Listbox]: Wrongly styled to fill content

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#863]
### Description

unlike other menu, listbox has a block flow and fully stretches filling the available space
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/15140652/204160020-6ddaa7d4-8cfe-43ae-adf3-66e2bc7b46bd.png">

### Component(s) impacted

listbox

### Vivid Web Components version

3.0.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

null

### CodeSandbox example

null

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rinaok** [comment]
@yinonov @rachelbt I remember that we've decided this in the PR on purpose right?
It's like in other components, for example: 

https://vivid.deno.dev/components/nav
https://vivid.deno.dev/components/accordion

**Comment by rachelbt** [comment]
not sure I fully understand. What is the desired behaviour?

**Comment by yinonov** [comment]
@rachelbt this
<img width="811" alt="image" src="https://user-images.githubusercontent.com/15140652/205879056-779e0306-a78b-41c9-ad34-211d72107e24.png">

**Comment by rachelbt** [comment]
Are you referring to the starch or the selected + hover bg colors?
In menu - it is inside popup that has width: fit-content.
here the author can control the with with the host or a wrapper element

**Comment by yinonov** [comment]
any reason for them to stretch fully by default? why not align with other components?

**Comment by rinaok** [comment]
> any reason for them to stretch fully by default? why not align with other components?

@yinonov  It's the same in other components, for example:

[vivid.deno.dev/components/nav](https://vivid.deno.dev/components/nav)
[vivid.deno.dev/components/accordion](https://vivid.deno.dev/components/accordion)

**Comment by rinaok** [comment]
@AyalaBu What do you think?

**Comment by AyalaBu** [comment]
@rinaok 
In option, nav-item & menu (vertical in this case) there is absolutely no reason to fully stretch the component.
Please view the design in this folder:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A80656&t=kxUDfOYQuYorXHv1-3

Also, the states are looking wrong:
1. _Hover_ state should be neutral **_50_**
2. _Selected_ state should be neutral _**100**_
3. _Pressed_ state should be neutral _**200**_

**Comment by yinonov** [comment]
Disregard information that isn't relevant to the display flow and online size

**Comment by rinaok** [comment]
@AyalaBu @yinonov Should we open a new issue about the states?

**Comment by AyalaBu** [comment]
@rinaok @yinonov Perhaps it should be a separate issue since it's dealing with a different appearance criteria?

**Comment by yinonov** [comment]
open a new issue please

**Comment by AyalaBu** [comment]
@yinonov @rinaok Done:

https://github.com/Vonage/vivid-3/issues/925
