### ISSUE TITLE
[textfield] leading action button

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#87]
feature request to support textfield leading action (button, textfield, select etc'...)
![image](https://user-images.githubusercontent.com/15140652/146912119-124c8547-fcfa-48b9-af96-f19799fa1673.png)

textfield currently supports **only** trailing actionable icon buttons (applying styles to slotted icon buttons)
![image](https://user-images.githubusercontent.com/15140652/146912849-dbcb7e58-9352-4d56-a3ed-8bd5872f7d78.png)

reasons to avoid extending textfield support:
- adding more action type support to textfield will overload its objective with multiple concerns.
- exposing a prefix, suffix slots will harm its ergonomics by breaking the lockdown

alternative option would be to separate concern with grouping controls (button, textfield, select etc'...) in an action/button group or any other dedicated component for that purpose.

**Comment by yinonov** [comment]
Toolbar?

**Comment by jshenkman** [comment]
Example from carbon
https://www.carbondesignsystem.com/patterns/search-pattern/

**Comment by jshenkman** [comment]
Examples for similar components 
1. Garden - [Input group](https://garden.zendesk.com/components/input-group)
![Screen Shot 2022-03-01 at 12 05 31](https://user-images.githubusercontent.com/67224525/156148889-434fc8cb-0b9d-4420-acb8-70a78a911982.png)

2.

**Comment by yinonov** [comment]
This is an architectural challenge of applying certain common variants (such as appearance - ghost) to the integral parts of select, textfield.
break down
- [ ] [textfield] appearance ghost support
- [ ] [select] state indication should be coherent with button ghost

following the above could be achieved with an elevation visual indication (of 0)

I suggest only applying this to vivid next as the integration of variants would be way easier than in vivid _< v3.0.0_
(or patch-hardcode current vivid)

**Comment by yinonov** [comment]
Handled in #350
