### ISSUE TITLE
[Ghost text-area]: adding ghost attribute for the text area component

### ISSUE THREAD

**Issue by TamirVonage** [Vonage/vivid-3#878]
### The problem

text area component has no ghost appearance option

### The solution

adding ghost attribute for the text area component

### Application/website

Chat components

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rachelbt** [comment]
> but text-area can't be used in action-group?

for what use? 
It was not meant for that.

**Comment by TamirVonage** [comment]
So I probably don't understand its purpose.
