### ISSUE TITLE
[progress-ring]: stroke-width

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#879]
wondering whether it right to change the `stroke-width` from 2px to 1px
![image](https://user-images.githubusercontent.com/7512792/205026200-71247267-c6ae-44e1-a184-7c30f7b65e84.png)

**Comment by AyalaBu** [comment]
@rachelbt I think it's better left 2px
If you change here then you need to change in checkbox too
And while 1px looks great in bigger components, in this case it somehow looks too gentle

**Comment by AyalaBu** [comment]
I think that the 1px looks better
But it is hard to be sure because I don't see it in action...

**Comment by rachelbt** [comment]
> I think that the 1px looks better But it is hard to be sure because I don't see it in action...

thats the whole point of this issue :zany_face:

**Comment by AyalaBu** [comment]
I think you should go for the 1px

**Comment by yinonov** [comment]
@rachelbt try `clamp`ing with 1px as minimum

**Comment by rachelbt** [comment]
> @rachelbt try `clamp`ing with `1px` as minimum

what for? clamp between 1 to 2px?
I don't think the 2px is needed

**Comment by yinonov** [comment]
oh. reduce it completely to 1px? go ahead

**Comment by rachelbt** [comment]
@AyalaBu WDYS?
https://vivid-9xy4qg6shvwg.deno.dev/components/progress-ring

**Comment by yinonov** [comment]
Looking good!

**Comment by AyalaBu** [comment]
I like it much more now!
