### ISSUE TITLE
[avatar]: unexpected template override

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#896]
The avatar has 3 options of content:

- icon (default icon ir a selected icon) - this is the default content
- name - if one sets a name property
- image - if one insert an image inside avatar - it overrides the template content of name or icon.

The problem
Because the default slot overrides the template if no image is inserted but there is a single space or a line break for the `</vwc-avatar>` it is interpreted as content causing the icon ot name to not being shown.

```<vwc-avatar shape="pill" ></vwc-avatar>```
give:
![image](https://user-images.githubusercontent.com/7512792/206387182-ccdcedb8-c526-4a18-a26f-410814dedd90.png)

```
<vwc-avatar shape="pill">
</vwc-avatar>
```
give:
![image](https://user-images.githubusercontent.com/7512792/206387350-9ea2796b-0155-418b-9d63-ca4de43cb157.png)

Options for solving
- adding a slot with name for the image
- adding a property/attribute of image to hide the template a show the image

**Comment by olaf-k** [comment]
I vote named slot!

**Comment by TamirVonage** [comment]
I vote named slot too :)
