### ISSUE TITLE
[helper message]: inconsistent design across organization

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#899]
### The problem

there are different design styles for control hints across the organization.

for text-field, text-area, number-field vivid components provide [helper text](https://vivid.deno.dev/components/text-field#helper-text) as a legacy and parity with versions < 3.x

other designs place a toggle-tip button adjacent to the label.

due to the nature of custom elements closed templates, authors can't place toggle-tips next to label

should both helper text and toggle-tip be supported? only one? which?

### The solution

should decide how to proceed from a design perspective

### Application/website

none

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by yinonov** [comment]
described in detail at #841

**Comment by rinaok** [comment]
@yinonov I think that if we have helper-text as a property in each component, we don't need a separate helper-text component anymore

**Comment by yinonov** [comment]
We don't have such a component in vivid@3

**Comment by rinaok** [comment]
@yinonov  I know that we don't have, I said that I think that the best solution is to add a helper-text attribute to each component.

**Comment by yinonov** [comment]
We do in inputs. Where else should we have it?

https://vivid.deno.dev/components/number-field#helper-text

**Comment by rinaok** [comment]
@yinonov Select, if I'll find another one I'll update

**Comment by yinonov** [comment]
Let's assume any element including a label could also have an adjacent tooltip / toggle-tip. That's actually the focus of this issue.
Moving ahead with this issue will first require a decision on whether to remove helper message in favour of that adjacent tip
