### ISSUE TITLE
[components]: icon line-height

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#904]
where the icon is set to be `font-size: 20px` its `line-height` is calculated to `28.5714px` this causing the icon to be aligned top a bit too much. 
The icon `line-height` need to be 1 (=20px). 
![image](https://user-images.githubusercontent.com/7512792/207251986-eca81a37-ec50-47d9-8d73-27c8ed91b9fd.png)

The line-height need to be set on the span wrapping the icon - the icon itself has its correct line-height
This effect the following components:
1. buttons
2. avatar
3. badge
4. banner
5. card
6. fab
7. menu-item (with check-box / radio)
8. option - there the font-size is set on the option - causing the line-height to be calculated on the entire option and making the option with text + icon to be height than 40px:
![image](https://user-images.githubusercontent.com/7512792/207254341-11ae8b23-031c-4543-b5d2-31eaab3fd844.png)
9. menu-item with icon
9. text-field with icon
may be more components that I missed

**Comment by rachelbt** [comment]
@yinonov maybe this is not icon related but token line-height calculation?

**Comment by yinonov** [comment]
good catch. should be patched in each of the composing elements, or, as @YonatanKra suggested, move patterned styles to the affix pattern to enforce consistency across integrations
