### ISSUE TITLE
[documentation]: meta tag image (for social) link is incorrect

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#905]
![image](https://user-images.githubusercontent.com/7512792/207268117-b35b7606-2e9c-4487-a6b8-495caa247263.png)

<`meta property="og:image" content="https://github.com/Vonage/vivid-3/blob/3ed7695e719b94bd87621983eba29c4d2df496e6/assets/images/vivid-logo.jpeg">`

should it be: 
https://raw.githubusercontent.com/Vonage/vivid-3/3ed7695e719b94bd87621983eba29c4d2df496e6/assets/images/vivid-logo.jpeg

**Comment by yinonov** [comment]
no. please replace to `https://raw.githubusercontent.com/Vonage/vivid-3/3ed7695e719b94bd87621983eba29c4d2df496e6/assets/images/vivid-logo.jpeg`

**Comment by yinonov** [comment]
yes should be replaced to the latter
