### ISSUE TITLE
[Dialog]: Adding separators

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#910]
There are a few layout designs for the dialog layout,
one of them contains a separators - it appears here:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19420%3A160156&t=mBYOHp9Om3VmCrkJ-3

I think that this feature is important, because it orders a content of the component.

related Jira ticket:
https://jira.vonage.com/browse/VIV-790

**Comment by rachelbt** [comment]
first question that need to be answered is weather we are adding the divider or are the consumers doing it with adding `vwc-divider.`

either way we need to extract the `inline-padding` from `main-wrapper` class  and have all 3 parts - header, content and footer.
We need to bear in mind that this also means that we need to no-render these parts if there's no content to avoid having un-necessary spaces. 

If we are implanting the divider - we need to decide if it is related to the header + footer, the content or regardless.

**Comment by yinonov** [comment]
what's the difference between the 2? when are dividers needed? when are they not? is there more than personal taste to it?

<img width="588" alt="image" src="https://user-images.githubusercontent.com/15140652/210251312-c78c436c-9b20-46cb-afb8-2ab5ac6b4d72.png">

**Comment by AyalaBu** [comment]
@rachelbt @yinonov 
Although the divider has an aesthetic function as well,
it also functions as an "order creator", since it divides the content to the easily understandable sections:
header, content & footer

**Comment by rachelbt** [comment]
So there will be an option with divider and without?

**Comment by AyalaBu** [comment]
I rechecked with Joella's original design an this is the situation:
1. Dialog with slotted content has separators
2. Dialog without slotted content doesn't

So these are the variants that need to exist:
![Screenshot 2023-01-03 at 13 58 51](https://user-images.githubusercontent.com/106529909/210353044-a16a5fa9-6fb3-4ea1-8542-97169f32a33e.png)

**Comment by rachelbt** [comment]
so we will either provide our users  top / bottom / both divider member or let them add it themselves but either way we need to adjust the padding issue.

**Comment by yinonov** [comment]
I'd still ask, why should an author decide whether to add dividers or not. It can be enforced conditionally when requirements are met, as mentioned, when header, body and footer are present

**Comment by AyalaBu** [comment]
This is what I wrote: the author doesn't decide.
1. Slotted content has dividers
2. No slotted content - no dividers

**Comment by rachelbt** [comment]
> I'd still ask, why should an author decide whether to add dividers or not. It can be enforced conditionally when requirements are met, as mentioned, when header, body and footer are present

or if there's only header and content...

**Comment by yinonov** [comment]
Ok. Sounds like a css work more than API

**Comment by rachelbt** [comment]
All of the examples on the right in Figma - that are suppose to reflect "no-content -> no divider" design are wrong. 
In the API we have header that contains icon-title-close button.
The text beneath the is the content of the dialog. 
So basically it will need to have a divider too.
![image](https://user-images.githubusercontent.com/7512792/210388451-d343d4b7-63e7-4751-9671-de08d98b79fb.png)

Maybe we need to start with turning the text member to be sub-title (https://github.com/Vonage/vivid-3/issues/911).

**Comment by yinonov** [comment]
Yes. That's the convention

**Comment by rachelbt** [comment]
after discussing with design as follow up to this[ Jira ticket](https://jira.vonage.com/browse/VIV-848) was decided that:
- If header contains subtitle than a bottom border will be added
- add a full-width body slot option
