### ISSUE TITLE
[Dialog]: adding subtitle

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#911]
There are a few layout designs for the dialog layout,
a few of them contain a subtitle - it appears here:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19420%3A160156&t=mBYOHp9Om3VmCrkJ-3

I think that this feature is important, and can be needed.

**Comment by rachelbt** [comment]
how long is the subtuitle? is it only one line and if longer it gets ellipsis?
or can it be multiple lines?

**Comment by yinonov** [comment]
Start simple. No extra styles

**Comment by rachelbt** [comment]
decided that:
- text will be changed to subtilte member and will be part of the dialog header (and will be styled as in Figma).
- content slot will be for dialog body content
