### ISSUE TITLE
[avatar]: proposal to add an additional appearance

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#920]
In addition to outline + filled we should consider adding duaton for delicate and more subtle design.
![image](https://user-images.githubusercontent.com/7512792/208391051-25e8c3d6-22aa-4dd5-b1b4-18682c6d6439.png)

**Comment by rachelbt** [comment]
@yinonov , @AyalaBu WDYS?

**Comment by yinonov** [comment]
why? was there a request?

**Comment by AyalaBu** [comment]
There will be soon.
Tamir spoke to me about adding this variant

**Comment by yinonov** [comment]
is this aligned with the team designing the chat?
anyway, there's no formal request, let's discuss when there is
