### ISSUE TITLE
[menu] extract work to feature light dismiss

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#921]
- [x] add `popover="auto"` (or `lightDismiss`) to menu
- [x] addEventListener to trigger close popup on menu `change` (1 of the items clicked)
- [x] add tests to ensure light dismiss work cross shadow boundaries

_Originally posted by @yinonov in https://github.com/Vonage/vivid-3/pull/765#discussion_r1053259500_

**Comment by rinaok** [comment]
After https://github.com/Vonage/vivid-3/pull/765 will be merged
