### ISSUE TITLE
[page layout]: Figma link placement in the website layout

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#932]
In order to avoid confusion with the designers the current idea was originated:

In every component page should be a link to direct Figma component.

The links place in the layout must be researched and checked to create a pleasant and easy to navigate layout

**Comment by AyalaBu** [comment]
@yinonov @rachelbt 
This the the design system I really liked, because it seems to be really easy to understand and navigate.

https://canvas.workday.com/components/buttons/button

I think we should consider adding links to Figma under the component name just like here 👆
It can have a link to the component itself,
and to the component's documentation.

What do you think?

**Comment by yinonov** [comment]
can you be more specific where the Figma embedded frame is? couldn't find it

**Comment by AyalaBu** [comment]
There isn't a Figma embedded frame
I meant that the link to Figma can be something like this: 

![Screenshot 2023-01-02 at 13 00 07](https://user-images.githubusercontent.com/106529909/210222704-691e3e96-7731-4420-b692-80f92c806b20.png)

**Comment by yinonov** [comment]
@Vonage/vivid WDYT? iframe / TAB or plain 'ol link to source.
I vote - link

**Comment by AyalaBu** [comment]
Although I am not a developer, I think that link is the best option.

**Comment by olaf-k** [comment]
I like tabs (which will involve an iframe anyway right?) since it lets me stay in place.

**Comment by rachelbt** [comment]
if the link is open only for Vonage users than maybe will use link to keep our documentation from having iframe with - "cant display this..."

**Comment by yinonov** [comment]
@AyalaBu what will it take to make ui kit public?

**Comment by AyalaBu** [comment]
Jay's approval
Having a meeting with him tomorrow

**Comment by yinonov** [comment]
so until that get's resolved, we can aim for links for a more suited UX. in the meantime, can we setup a table for figma links for each of the components?

| component | figma component link | figma component documentation link
|---|---|---|
Button       |                 x                    |                    x

**Comment by AyalaBu** [comment]
A file was opened to include this information :

https://docs.google.com/document/d/1EjZo3VTbfz381h9pKcm0g8mJ35hSjTVI022XTBHOAkI/edit?usp=sharing
