### ISSUE TITLE
[Helper text]: is this property needed?

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid-3#938]
### The problem

helper text is a property inherited from legacy API to present additional information providing extra ability to communicate and give clarity to a user on a form control.

in practice, the text is added underneath a control adding no-semantic relation but pure context (text only)

Such text can be easily added by authors and reduce API complexity

#899 suggests a different approach to populate hint via tooltips / toggletips

### The solution

remove helper text

### Application/website

null

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Examples

text field, number field etc'.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/vonage/vivid-3/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/vonage/vivid-3/issues) for duplicate issues

**Comment by rinaok** [comment]
@yinonov VBC and other teams uses it so I think that we should continue supporting it if we want them to migrate components from vivid-2 to vivid-next

**Comment by yinonov** [comment]
I don't really know why they use it but it can easily be replaced with plain text as it adds nothing more than a styled text. Once we include core styles in VBC...

**Comment by rinaok** [comment]
https://jira.vonage.com/browse/VIV-1000
