### ISSUE TITLE
[documentation]: getting started

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid-3#939]
as a result of working with Karin from meeting trying to integrate vivid-next in meeting summarizing our workflow: 

- how do I know which version am I installing? (we can rune this: `npm view @vonage/vivid`), but once we are GA we should have the latest version in our docs.

- **installing:**
problem: Currently the install line in vivid is running over the vivid-2 installation
this `npm install @vonage/vivid # or yarn add @vonage/vivid` need to be changed to: 
- add this in package.json: `@vonage/vivid": "3.0.0-next.123`
or:
- npm i @vonage/vivid@next

if one project has all vivid-2 installed (and not separated components) and want to add vivid next the install need to include - alias? (need to verify this with @YonatanKra )

- **after installing vivid-next** 
need add the components you want. If prefix is needed - the need to be added to the project to each component that are added:

```
import { registerNote } from '@vonage/vivid';
registerNote('vwc3');
```
**for adding the styles and tokens:**
add this in the main css project file:
```
@import "~@vonage/vivid/styles/core/all"
@import "~@vonage/vivid/styles/tokens/theme-light.css"
```

all this is not enough - it will have no impact id the class `vvd-root` will not be added!

* we didn't install the latest version so no font reference here.

**comments:**
- we managed inserting vivd-2 component inside vivid-next all wend great!
- once installation was done - all went smooth and easy 
- vivd-next installation made the project serve slow
- the inconsistency between the api and the Figma effects not only the designers but also devs. There's no correlation between the style, slots and naming the parts. 

**Action items:**

- [ ] change the installation in the getting started
- [ ] add instruction if all vivid-2 is installed or only components
- [ ] more clear code snippets about adding the style imports
- [ ] aligning Figam to the API - a headline that will need to be break into small pieces I guess :)

**Comment by yinonov** [comment]
all information is already documented only it scattered and need to be mirrored in a single migration guide doc page

How to integrate vivid@3 while still keep vivid@2 existing integrated components (only need to add [the part](https://github.com/Vonage/vivid-3/issues/939#issuecomment-1372494568) @rinaok mentioned)

https://github.com/Vonage/vivid-3/blob/8ec68c05d1e530723080289120039c0cc774460b/libs/components/README.md?plain=1#L85-L94

how to include the css files (tokens / styles)
https://github.com/Vonage/vivid-3/blob/8ec68c05d1e530723080289120039c0cc774460b/libs/components/README.md?plain=1#L38

**Comment by rachelbt** [comment]
was dont in this PR:
https://github.com/Vonage/vivid-3/pull/1007
