### ISSUE TITLE
[Component review]: new UI Kit - Button

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#944]
This is the new UI Kit file link:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=74%3A476&t=LvF6HVAi27u53KjZ-1

Since the new file is featuring some changes the review is in order.
A review of a **button component** will be appreciated:

https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19313%3A96310&t=LvF6HVAi27u53KjZ-1

**Comment by rachelbt** [comment]
@AyalaBu I suggest you'll separate to each component a new issue.
Button (only buttons):
- Anatomy:
-- there's no container to the button any more.
-- change text label to label (same as in the API)
- icon - the default is leading. For  trailing need to add `icon-trailing`
- size - use sizes as API (condensed' | 'normal' | 'expanded')
- types / Variant - again - stick to the API naming of size
- didn't see any disabled design for button
