### ISSUE TITLE
[breaking changes in components]: research on how should be treated

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#945]
Sometimes we have a breaking changes to the components,
which are supposed to be shown in the Figma file as well.

This can present an issue to the designers that work with the components:
If a specific component is implemented in the designs is suddenly changed, then it can change the design altogether.

So what progress should happen before the change?
How should the change be treated?

Just a point for consideration:
there is a Figma versioning system plugin that may be considered as a solution:

https://medium.com/eightshapes-llc/versioning-design-systems-48cceb5ace4d

https://www.figma.com/community/plugin/1046106377087666849/Semantic-Versioning

So what are your thoughts on this?

**Comment by yinonov** [comment]
Breaking changes are most severe as they can remove support of features but any change in general could affect components. How does Figma components handle version control? This should be discussed with design team and a process should be documented
