### ISSUE TITLE
[Dialog]: modal

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid-3#972]
- [x] #973
- [x] The color of the modal should be darker. [added in the PR](https://github.com/Vonage/vivid-3/pull/971)

**Comment by AyalaBu** [comment]
I think it should be added and edited to be:
1. color neutral 950
2. opacity 0.5

Just like in this example:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/Vivid-UI-Kit---3.0-WIP?node-id=19505%3A134565&t=7Z3pk8f4gDCjQ3TG-1

**Comment by rachelbt** [comment]
@AyalaBu 
We cant use the tokens in the dialog::backdrop.
I used the `currenColor` function - which takes the canvas-text color that is set on the dialog (which is now the same as in vivid-2)
see here: https://vivid-nnsg4xd7gdf0.deno.dev/components/dialog#showmodal

**Comment by AyalaBu** [comment]
I think it looks much better this way,
and it will be easier for the users to understand what's going on on the screen
