### ISSUE TITLE
[card variants]: creating selectable card

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#985]
Lately turned out to be multiple examples of a card components added by designers but sadly not present in Vivid and showing various behaviors.

![Image](https://user-images.githubusercontent.com/106529909/215329311-9799bad3-620b-43aa-91e2-e137f6d01ade.png)

![Image](https://user-images.githubusercontent.com/106529909/215329337-3af73abe-a113-4f96-9744-13ba05531458.png)

![Image](https://user-images.githubusercontent.com/106529909/215329370-820aacc0-be57-45f9-be89-e353ba2cf471.png)

After a discussion with Jay a decision was reached that all of these components must be unified under the same component.

These are some examples of clickable UI cards I saw:

https://design.principal.com/ux/components/selection-cards

https://ux.stackexchange.com/questions/125068/improving-ux-for-multi-selectable-cards

So how do we treat this situation?

**Comment by yinonov** [comment]
be advised this component's features and constraints should completely align with the [listbox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/).
consider this as a visually enhanced option representation (same as selectmenu option) and is recommended to comply with its rules
<img width="155" alt="image" src="https://user-images.githubusercontent.com/15140652/215329651-430167ec-b8b3-435c-8937-141b21b46f8d.png">

e.g. 
> Avoiding very long option names facilitates understandability and perceivability for screen reader users. The entire name of an option is spoken as a single unit of speech when the option is read. When too much information is spoken as the result of a single key press, it is difficult to understand. Long names inhibit perception by increasing the impact of interrupted speech because users typically have to re-read the entire option. And, if the user does not understand what is spoken, reading the name by character, word, or phrase may be a difficult operation for many screen reader users in the context of a listbox widget.
