### ISSUE TITLE
[option item]: creating variant with different layout

### ISSUE THREAD

**Issue by AyalaBu** [Vonage/vivid-3#986]
Lately it came to my attention that another option item was created with a different layout:

![Image](https://user-images.githubusercontent.com/106529909/215329661-6333a3b7-75e9-461b-a6ed-846f9062ba49.png)

![Image](https://user-images.githubusercontent.com/106529909/215329705-1078b99b-257a-4895-9e23-7a0db144b25c.png)

While having a discussion I said that this is basically and option item, and why not to use something that we already have.
The reply was:

1.  That it's less nicer looking with the existing layout
2. It was already developed
3. Everyone loves it (?)

So how do we treat this situation?

**Comment by yinonov** [comment]
> That it's less nicer looking with the existing layout

Might be a valid argument. Due that reason alone, it is being considered in vivid.

> It was already developed

With no proper research? a wrong process

> Everyone loves it (?)

How is this measured? Can the benchmark be shared?

**Comment by AyalaBu** [comment]
@yinonov @rinaok @rachelbt @YonatanKra @olaf-k 

I found a components with somewhat similar layout in the material and angular:

https://mui.com/material-ui/react-checkbox/#label-placement

https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

I guess it is something that can be considered, although it didn't appear in most of design systems I looked at.
What are your thought about this?

**Comment by AyalaBu** [comment]
This is the link to branch with the component draft:
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/branch/XvcpSELq5h93tA72JqErzj/Vivid-UI-Kit---3.0-WIP?node-id=19073%3A77181&t=4MpnyNf0dl8EQQiI-1

The component was approved by designers.

These are links that take to a specific frames:
**Checkbox:**
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/branch/XvcpSELq5h93tA72JqErzj/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81005&t=4MpnyNf0dl8EQQiI-1

**Radio:**
https://www.figma.com/file/JJNgZvt1qf3ydYmOwbE3Jg/branch/XvcpSELq5h93tA72JqErzj/Vivid-UI-Kit---3.0-WIP?node-id=19097%3A81022&t=4MpnyNf0dl8EQQiI-1

**Comment by AyalaBu** [comment]
Moved to JIRA:
https://jira.vonage.com/browse/VIV-954
